# Copyright 2018-2026 H2O.ai, Inc. All rights reserved.
import json
import traceback

import airium
import datatable

from h2o_sonar.lib.api import commons
from h2o_sonar.lib.api import datasets
from h2o_sonar.lib.api import evaluators
from h2o_sonar.lib.api import explanations as e10s
from h2o_sonar.lib.api import formats as f5s
from h2o_sonar.lib.api import models
from h2o_sonar.lib.api import problems
from h2o_sonar.lib.api import results
from h2o_sonar.utils import progress as progress_utils


try:
    import jsonschema

    HAS_JSONSCHEMA = True
except ImportError:
    HAS_JSONSCHEMA = False


# aliases
BoolLeaderboard = e10s.LlmBoolLeaderboardExplanation


class JSONSchemaEvaluator(evaluators.Evaluator):
    _display_name = "JSON Schema"
    _tagline = "Evaluate the answers against JSON schema."

    # COMPATIBILITY: LLM/RAG evaluation
    _rag = True
    _llm = True  # evaluator does NOT require context

    # GLOBAL EXPLANATIONS support
    _global_explanation = True

    # EXPLANATION TYPES created by the evaluator
    _explanation_types = [
        e10s.LlmEvalResultsExplanation,
        e10s.LlmBoolLeaderboardExplanation,
        e10s.WorkDirArchiveExplanation,
    ]

    # KEYWORDS to find this evaluator when listing / filtering evaluators
    _keywords = [
        evaluators.KEYWORD_LLM,
        evaluators.KEYWORD_EVALUATES_RAG,
        evaluators.KEYWORD_EVALUATES_LLM,
        evaluators.KEYWORD_RQ_AA,
        evaluators.KEYWORD_SR_11_7_CS,
        evaluators.KEYWORD_SR_11_7_OGA,
        evaluators.KEYWORD_SR_11_7_OA,
        evaluators.KEYWORD_NIST_AI_RMF_S,
        evaluators.KEYWORD_NIST_AI_RMF_SR,
        evaluators.KEYWORD_NIST_AI_RMF_PE,
        evaluators.KEYWORD_NIST_AI_RMF_F,
        evaluators.KEYWORD_NIST_AI_RMF_AT,
        evaluators.KEYWORD_NIST_AI_RMF_VR,
        evaluators.KEYWORD_PROBLEM_TYPE_IR,
        evaluators.KEYWORD_PROBLEM_TYPE_QA,
        evaluators.KEYWORD_PROBLEM_TYPE_SUM,
        evaluators.KEYWORD_PROBLEM_TYPE_REG,
        evaluators.KEYWORD_PROBLEM_TYPE_CLS,
        evaluators.KEYWORD_PROBLEM_TYPE_BIN,
        evaluators.KEYWORD_PROBLEM_TYPE_MUL,
        evaluators.KEYWORD_ES_GENERATE,  # required for H2O Eval Studio eval eye
        evaluators.KEYWORD_METHOD_RULE_BASED,
        evaluators.KEYWORD_METHOD_TYPE_DETERMINISTIC,
        evaluators.KEYWORD_CAP_CH,
    ]

    _metrics_meta = BoolLeaderboard.LEADERBOARD_METRICS_META.copy_with_overrides(
        {
            BoolLeaderboard.METRIC_MODEL_PASSES: {
                commons.MetricMeta.KEY_DISPLAY_NAME: "Valid JSON (pass)",
                commons.MetricMeta.KEY_DESCRIPTION: (
                    "Percentage of successfully validated RAG/LLM outputs against the "
                    "JSON Schema."
                ),
            },
            BoolLeaderboard.METRIC_MODEL_FAILURES: {
                commons.MetricMeta.KEY_DISPLAY_NAME: "Invalid JSON (fail)",
                commons.MetricMeta.KEY_DESCRIPTION: (
                    "Percentage of RAG/LLM outputs that failed to validate against the "
                    "JSON Schema."
                ),
            },
            BoolLeaderboard.METRIC_MODEL_RETRIEVAL_FAILURES: {
                commons.MetricMeta.KEY_DISPLAY_NAME: "Invalid retrieved JSON",
                commons.MetricMeta.KEY_DESCRIPTION: (
                    "JSON fragments in RAG's retrieved contexts are not JSON Schema "
                    "validated."
                ),
            },
            BoolLeaderboard.METRIC_MODEL_GENERATION_FAILURES: {
                commons.MetricMeta.KEY_DISPLAY_NAME: "Invalid generated JSON",
                commons.MetricMeta.KEY_DESCRIPTION: (
                    "Percentage of successfully JSON Schema validated outputs "
                    "generated by RAG/LLM (equivalent to the model failures)."
                ),
            },
            BoolLeaderboard.METRIC_MODEL_PARSE_FAILURES: {
                commons.MetricMeta.KEY_DISPLAY_NAME: "Parsing failures",
                commons.MetricMeta.KEY_DESCRIPTION: (
                    "Percentage of RAG/LLM outputs that evaluator's judge "
                    "(LLM, RAG or model) was unable to parse, and therefore unable to "
                    "evaluate and provide a metrics score for "
                    "Invalid JSON metric which detects JSON Schema validation errors."
                ),
                commons.MetricMeta.KEY_EXCLUDE: True,
            },
        },
    )

    # EVALUATOR PARAMETERS
    PARAM_JSON_SCHEMA: str = "json_schema"
    PARAM_JSON_SCHEMA_DEFAULT: str = "{}"  # all JSONs validate against this schema
    _parameters = [
        evaluators.EvaluatorParam(
            param_name=PARAM_JSON_SCHEMA,
            param_type=commons.EvaluatorParamType.str,
            description=(
                "JSON Schema evaluator validates actual answers against the schema "
                "specified by https://json-schema.org/specification and provided by "
                "this parameter. If JSON Schema not specified (is {}), then the "
                "evaluator just checks parseability and assumes all JSONs valid."
            ),
            default_value=PARAM_JSON_SCHEMA_DEFAULT,
        ),
        evaluators.Evaluator._get_custom_param_metric_threshold(
            _metrics_meta.get_primary_metric()
        ),
        evaluators.Evaluator._PARAM_SAVE_LLM_RESULT,
    ]

    _brief_description = """JSON Schema Evaluator assesses whether actual answers
are valid if validated against given JSON Schema:

* https://json-schema.org/specification.
"""
    _description = evaluators.Evaluator._description_builder(
        brief=f"""{_brief_description}

**Example**:

Consider the following JSON Schema which specifies both types and particular
values for the ``price`` and ``code`` fields:

```json
{{
  "type": "object",
  "properties": {{
    "product": {{
      "type": "object",
      "properties": {{
        "details": {{
          "type": "object",
          "properties": {{
            "price": {{"type": "number", "const": 314}}, # price must be exactly 314
            "code": {{"type": "string", "const": "at42"}} # code must be exactly "at42"
          }},
          "required": ["price", "code"]
        }}
      }},
      "required": ["details"]
    }}
  }},
  "required": ["product"]
}}
```

**Method**:

- The evaluator parses and evaluates the JSON actual answers using the JSON Schema
  validator.
- If the JSON Schema is not provided (parameter is set to ``{{}}``), then the evaluator
  just checks if the actual answers are parseable JSON strings.""",
        metrics_meta=_metrics_meta,
        keywords=_keywords,
        parameters=_parameters,
        leaderboard_type=e10s.LlmBoolLeaderboardExplanation.explanation_type(),
    )

    def __init__(self):
        evaluators.Evaluator.__init__(self)

        self.args = None
        self.problems = []
        self.log_name = "JSON Schema evaluator"

    def check_compatibility(
        self,
        params: commons.CommonInterpretationParams | None = None,
        **evaluator_params,
    ) -> bool:
        evaluators.Evaluator.check_compatibility(self, params, **evaluator_params)

        if not HAS_JSONSCHEMA:
            self.logger.warning(
                f"{self.log_name}: jsonschema Python package not installed - NOT "
                f"COMPATIBLE"
            )
            return False

        if not self.models:
            self.logger.warning(
                f"{self.log_name}: no RAG/LLM models found for evaluation: "
                f"{[m.key for m in self.models]} - NOT COMPATIBLE"
            )
            return False

        # IMPROVE check dataset columns presence & actual values (non-empty)
        # IMPROVE document column names in the evaluator description

        if not evaluators.Evaluator._check_llm_dataset_compatibility(
            self, params=params, evaluator_keywords=self._keywords
        ):
            return False

        # check that at least one row has actual answer
        if not self._check_llm_dataset_field_presence(
            params=params,
            require_actual_answer=True,
            require_expected_answer=False,
        ):
            return False

        return True

    def setup(self, model, persistence, **kwargs):
        evaluators.Evaluator.setup(self, model, persistence, **kwargs)

        self._resolve_evaluator_params()

        self.log_name = f"JSON Schema evaluator {self.mli_key}/{self.key}"

    def evaluate(self, llm_testset, **kwargs) -> list:
        # RAG models: key -> model
        key_2_evaluated_model = {m.key: m for m in self.models}
        # LLM host: RAG or service
        llm_host = (
            commons.LlmModelHostType.RAG
            if isinstance(
                next(iter(key_2_evaluated_model.values())), models.ExplainableRagModel
            )
            else commons.LlmModelHostType.SERVICE
        )
        llm_host_str = "RAG" if llm_host == commons.LlmModelHostType.RAG else "LLM"

        # extract JSON Schema
        json_schema_str = self.args.get(
            JSONSchemaEvaluator.PARAM_JSON_SCHEMA,
            JSONSchemaEvaluator.PARAM_JSON_SCHEMA_DEFAULT,
        )
        # JSON Schema must be valid JSON
        json_schema = {}
        json_schema_valid = False
        try:
            json_schema = json.loads(json_schema_str)
            json_schema_valid = True
        except Exception as ex:
            html = airium.Airium()
            html(
                "JSON Schema provided as JSON Schema evaluator parameter is "
                "invalid. It is not well formed JSON string: "
            )
            with html.code():
                html(f"{ex}")
            with html.code():
                html(f">>>{json_schema_str}<<<")
            problem = problems.ProblemAndAction(
                description=(
                    f"JSON Schema provided as JSON Schema evaluator parameter is "
                    f"invalid. It is not well formed JSON string: {ex} "
                    f">>>{json_schema_str}<<<"
                ),
                description_html=html,
                problem_type="parameters",
                problem_code=problems.AVIDProblemCode.P0100_DATA,
                problem_attrs={
                    "explainer_id": JSONSchemaEvaluator.evaluator_id(),
                },
                severity=problems.ProblemSeverity.high,
                actions_description=(
                    "Provide valid JSON Schema as the evaluator parameter."
                ),
                evaluator_id=JSONSchemaEvaluator.evaluator_id(),
                evaluator_name=JSONSchemaEvaluator._display_name,
                resources=[],
            )
            self.add_problem(problem)

        #
        # EVALUATION
        #
        if json_schema_valid:
            eval_results = self._eval_test_cases(
                llm_dataset_as_dt=llm_testset,
                json_schema=json_schema,
            )
        else:
            eval_results = datasets.LlmEvalResults()
            llm_dataset = datasets.LlmDataset.from_datatable_dict(llm_testset.to_dict())
            for e, r in enumerate(llm_dataset.inputs):
                # add to result
                eval_results.add_result(
                    datasets.LlmEvalResults.LlmEvalResultRow(
                        dataset_row=r,
                        metrics={
                            BoolLeaderboard.KEY_RESULT_CHECK_OK: 0.0,
                            BoolLeaderboard.KEY_RESULT_CHECK_FAIL: 1.0,
                            BoolLeaderboard.KEY_RESULT_CHECK_FAIL_R: 0.0,
                            BoolLeaderboard.KEY_RESULT_CHECK_FAIL_A: 0.0,
                            BoolLeaderboard.KEY_RESULT_CHECK_FAIL_P: 0.0,
                            BoolLeaderboard.KEY_RESULT_CHECK_ERR_MSG: (
                                f"Unable to validate actual answer because the "
                                f"JSON Schema provided in the evaluator parameter "
                                f"is invalid: >>>{json_schema_str}<<<"
                            ),
                        },
                        actual_output_meta=None,
                    )
                )

        #
        # NORMALIZATION of the evaluation RESULTS
        #

        # EXPLANATIONS
        explanations = []

        # EXPLANATION: all data (per prompt metrics)
        if self.args.get(
            evaluators.Evaluator.PARAM_SAVE_LLM_RESULT,
            evaluators.Evaluator.DEFAULT_SAVE_LLM_RESULT,
        ):
            eval_results_explanation = e10s.LlmEvalResultsExplanation(
                evaluator=self,
                display_name="JSON Schema evaluation results",
                display_category=e10s.Explanation.DISPLAY_CAT_LLM,
                eval_results=eval_results,
            )
            # FORMATS of the explanation: JSON, CSV, DataTable
            eval_results_explanation.add_json_format()
            eval_results_explanation.add_csv_format()
            eval_results_explanation.add_datatable_format()
            explanations.append(eval_results_explanation)

        # EXPLANATION: ok/fail leaderboard
        t_bool_leaderboard = e10s.LlmBoolLeaderboardExplanation
        leaderboard_explanation = t_bool_leaderboard.from_eval_results(
            evaluator=self,
            eval_results=eval_results,
            metrics_meta=self._metrics_meta,
            metric_id_success=t_bool_leaderboard.KEY_RESULT_CHECK_OK,
            metric_id_failure_message=t_bool_leaderboard.KEY_RESULT_CHECK_ERR_MSG,
            display_name="RAG benchmark leaderboard",
            display_category=e10s.GlobalSummaryFeatImpExplanation.DISPLAY_CAT_LLM,
            key_2_evaluated_model=key_2_evaluated_model,
            llm_host=llm_host,
            do_eval_rc=False,
            logger=self.logger,
        )
        # FORMAT of the explanation: Markdown
        leaderboard_explanation.add_markdown_format(title=f"{llm_host_str} Report")
        leaderboard_explanation.add_evalstudio_markdown_format(title="Summary")
        leaderboard_explanation.add_json_format(
            llm_host=llm_host,
            threshold=self.args.get(
                evaluators.Evaluator.PARAM_METRIC_THRESHOLD,
                leaderboard_explanation.METRIC_META_MODEL_PASSES.threshold,
            ),
        )
        explanations.append(leaderboard_explanation)

        # PROBLEMS for alerts and actionability
        self._diagnose_problems(
            leaderboard_explanation=leaderboard_explanation,
            eval_results=eval_results,
            key_2_evaluated_model=key_2_evaluated_model,
        )

        # INSIGHTS
        JSONSchemaEvaluator._diagnose_insights(
            leaderboard_explanation=leaderboard_explanation
        )

        # EXPLANATION: HTML fragment
        if self.config and self.config.create_html_representations:
            try:
                html_explanation = e10s.GlobalHtmlFragmentExplanation(
                    evaluator=self,
                    display_name=f"{llm_host_str} leaderboard as HTML",
                    display_category=e10s.Explanation.DISPLAY_CAT_COMPLIANCE,
                )
                html_explanation.add_html_format(str(leaderboard_explanation.as_html()))
                explanations.append(html_explanation)
            except Exception as ex:
                self.logger.warning(
                    f"{self.log_name}: HTML fragment explanation creation failed: "
                    f"{ex}\n{traceback.format_exc()}",
                )

        # EXPLANATION: ZIP archive of all artifacts created by the evaluator
        explanations.append(
            self.create_explanation_workdir_archive(
                display_name=f"Archive of {self._display_name} artifacts",
                display_category=e10s.Explanation.DISPLAY_CAT_COMPLIANCE,
            )
        )

        return explanations

    @staticmethod
    def validate_str_against_json_schema(s: str, json_schema: dict) -> tuple[bool, str]:
        # input string sanity check
        if not s:
            return False, "Actual answer is empty"
        try:
            parsed_s = json.loads(s)
        except Exception as ex:
            return False, f"Actual answer cannot be parsed as JSON: {ex}"

        if not json_schema:
            return True, ""  # any JSON is compliant with the empty schema

        # JSON Schema validation
        try:
            jsonschema.validate(instance=parsed_s, schema=json_schema)
            return True, ""
        except jsonschema.exceptions.ValidationError as eex:
            return False, f"Actual answer is not valid against given JSON Schema: {eex}"
        except Exception as eeex:
            return False, (
                f"Actual answer cannot be validated against given JSON Schema: {eeex}"
            )

    @staticmethod
    def _eval_against_json_schema(
        actual_output: str,
        json_schema: dict,
    ) -> tuple[float, str]:
        # handle actual answer retrieval error ~ RAG/LLM client crash
        if evaluators.Evaluator._is_internal_err_answer(actual_output):
            # set WORST metrics values
            return (
                0.0,  # OK
                evaluators.Evaluator._internal_err_answer_msg(err_msg=actual_output),
            )

        # evaluate ANSWER
        (answer_result, validation_err_msg) = (
            JSONSchemaEvaluator.validate_str_against_json_schema(
                s=actual_output,
                json_schema=json_schema,
            )
        )

        return (
            1.0 if answer_result else 0.0,
            validation_err_msg,
        )

    def _eval_test_cases(
        self,
        llm_dataset_as_dt: datatable.Frame,
        json_schema: dict,
    ) -> datasets.LlmEvalResults:
        llm_dataset = datasets.LlmDataset.from_datatable_dict(
            llm_dataset_as_dt.to_dict()
        )
        eval_results = datasets.LlmEvalResults()

        self.report_progress(
            0.01,
            (
                f"Checking {len(llm_dataset.inputs)} test cases validity against "
                f"JSON Schema"
            ),
        )

        #
        # EVALUATION
        #
        for e, r in enumerate(llm_dataset.inputs):
            self.eval_tc_json_validity(
                row=r,
                json_schema=json_schema,
                eval_results=eval_results,
            )

            # progress
            self.report_progress(
                progress=progress_utils.ProgressCallbackContext.progress_for_steps(
                    e + 1, len(llm_dataset.inputs)
                ),
                message=(
                    f"Checked {e + 1}/{len(llm_dataset.inputs)} test cases JSON "
                    f"validity"
                ),
            )

        return eval_results

    def eval_tc_json_validity(
        self,
        row: datasets.LlmDataset.LlmDatasetRow,
        json_schema: dict,
        eval_results: datasets.LlmEvalResults,
    ):
        t_bool_leaderboard = e10s.LlmBoolLeaderboardExplanation

        # handle edge case: empty or non-string actual output
        if not row.actual_output or not isinstance(row.actual_output, str):
            description = (
                f"Empty or invalid actual output detected for test case. "
                f"Actual output: {row.actual_output}. "
                f"Setting worst metric values (non-compliant)."
            )
            self.logger.warning(description)

            self.add_problem(
                problems.ProblemAndAction(
                    description=description,
                    severity=problems.ProblemSeverity.low,
                    evaluator_id=self.evaluator_id(),
                    problem_attrs={
                        problems.ProblemAndAction.ATTR_ROW_KEYS: [
                            (row.key, row.model_key)
                        ],
                        problems.ProblemAndAction.ATTR_TEST_CASE_KEYS: [row.key],
                        problems.ProblemAndAction.ATTR_EVALUATOR_NAME: (
                            self._display_name
                        ),
                    },
                    evaluator_name=self._display_name,
                    explanation_type=(
                        e10s.GlobalHtmlFragmentExplanation.explanation_type()
                    ),
                    explanation_name=e10s.GlobalHtmlFragmentExplanation.__name__,
                    explanation_mime=f5s.HtmlFormat.mime,
                    resources=[],
                )
            )

            # set WORST metrics values: non-compliant
            eval_results.add_result(
                datasets.LlmEvalResults.LlmEvalResultRow(
                    dataset_row=row,
                    metrics={
                        t_bool_leaderboard.KEY_RESULT_CHECK_OK: 0.0,
                        t_bool_leaderboard.KEY_RESULT_CHECK_FAIL: 1.0,
                        t_bool_leaderboard.KEY_RESULT_CHECK_FAIL_R: 0.0,
                        t_bool_leaderboard.KEY_RESULT_CHECK_FAIL_A: 1.0,
                        t_bool_leaderboard.KEY_RESULT_CHECK_FAIL_P: 0.0,
                        t_bool_leaderboard.KEY_RESULT_CHECK_ERR_MSG: (
                            "Actual output is empty or not a string"
                        ),
                    },
                    actual_output_meta=None,
                )
            )
            return

        (
            ok,
            err_msg,
        ) = JSONSchemaEvaluator._eval_against_json_schema(
            actual_output=row.actual_output,
            json_schema=json_schema,
        )

        # add to result
        eval_results.add_result(
            datasets.LlmEvalResults.LlmEvalResultRow(
                dataset_row=row,
                metrics={
                    t_bool_leaderboard.KEY_RESULT_CHECK_OK: ok,
                    t_bool_leaderboard.KEY_RESULT_CHECK_FAIL: 0.0 if ok else 1.0,
                    t_bool_leaderboard.KEY_RESULT_CHECK_FAIL_R: 0.0,
                    t_bool_leaderboard.KEY_RESULT_CHECK_FAIL_A: 1.0 if not ok else 0.0,
                    t_bool_leaderboard.KEY_RESULT_CHECK_FAIL_P: 0.0,
                    t_bool_leaderboard.KEY_RESULT_CHECK_ERR_MSG: err_msg,
                },
                actual_output_meta=None,
            )
        )

    @staticmethod
    def _diagnose_insights(
        leaderboard_explanation: e10s.LlmBoolLeaderboardExplanation,
    ):
        t_html_fragment = e10s.GlobalHtmlFragmentExplanation

        leaderboard_explanation.get_insights(
            extra_description_actions=(
                "Check the prompt, expected answer and JSON Schema - are they "
                "correct? Check models answers in failed cases and look for a "
                "common denominator or root cause of these failures."
            ),
            explanation_type=t_html_fragment.explanation_type(),
            explanation_name=t_html_fragment.__name__,
            explanation_mime=f5s.HtmlFormat.mime,
        )

    def _diagnose_problems(
        self,
        leaderboard_explanation: e10s.LlmBoolLeaderboardExplanation,
        eval_results: datasets.LlmEvalResults,
        key_2_evaluated_model: dict,
    ):
        # perturbation flips
        self._diagnose_perturbation_problems(
            eval_results=eval_results,
            key_2_evaluated_model=key_2_evaluated_model,
        )

        # threshold failures
        problems.problems_for_bool_leaderboard(
            evaluator=self,
            leaderboard=leaderboard_explanation,
            metric_threshold=self.args.get(
                evaluators.Evaluator.PARAM_METRIC_THRESHOLD,
                leaderboard_explanation.METRIC_META_MODEL_PASSES.threshold,
            ),
            primary_metric_meta=leaderboard_explanation.METRIC_META_MODEL_PASSES,
            problem_type="accuracy",
            problem_code=problems.AVIDProblemCode.P0200_MODEL,
            actions_description=(
                "For all failed test cases, check the prompt, expected answer, and "
                "JSON Schema to see if they are correct. Then, examine the model's "
                "answers in the failed cases and look for a common denominator or "
                "root cause of these failures."
            ),
            explanation_type=e10s.GlobalHtmlFragmentExplanation.explanation_type(),
            explanation_name=e10s.GlobalHtmlFragmentExplanation.__name__,
            explanation_mime=f5s.HtmlFormat.mime,
        )

    def get_result(
        self,
    ) -> results.LeaderboardResult:
        return results.LeaderboardResult(
            persistence=self.persistence,
            explainer_id=JSONSchemaEvaluator.explainer_id(),
            h2o_sonar_config=self.config,
            logger=self.logger,
            explanation=e10s.LlmBoolLeaderboardExplanation,
            explanation_format=f5s.CustomJsonFormat,
        )
