# Copyright 2018-2026 H2O.ai, Inc. All rights reserved.
from h2o_sonar.evaluators import abc_byop_evaluator
from h2o_sonar.lib.api import commons
from h2o_sonar.lib.api import evaluators
from h2o_sonar.lib.api import explanations as e10s
from h2o_sonar.lib.api import problems


# aliases
BoolLeaderboard = e10s.LlmBoolLeaderboardExplanation


class LanguageMismatchByopEvaluator(abc_byop_evaluator.AbcByopEvaluator):
    _display_name = "Language mismatch"
    _tagline = "Detect language mismatch between the question and actual answer."

    _CLASSES = abc_byop_evaluator.AbcByopEvaluator.Classes(
        failure="different", success="same"
    )

    _PROBLEM_THRESHOLD_PROTO = problems.ProblemAndAction(
        description="",
        problem_type="accuracy",
        problem_code=problems.AVIDProblemCode.P0200_MODEL,
        actions_description=(
            "Try to improve context awareness in the models by incorporating advanced "
            "attention mechanisms and external context. Additionally, question "
            "reformulation techniques like clarification modules and interactive "
            "questioning can bridge the gap. Finally, improved answer presentation "
            "through summarization and justification can ensure the answer "
            "directly addresses the user's intent. These efforts, along with "
            "high-quality training data and potential human oversight, will "
            "lead to more natural and informative interactions between users "
            "and LLMs/RAGs."
        ),
        severity=problems.ProblemSeverity.medium,
    )

    _metrics_meta = BoolLeaderboard.LEADERBOARD_METRICS_META.copy_with_overrides(
        {
            BoolLeaderboard.METRIC_MODEL_PASSES: {
                commons.MetricMeta.KEY_DISPLAY_NAME: "Same language (pass)",
                commons.MetricMeta.KEY_DESCRIPTION: (
                    "Percentage of successfully evaluated RAG/LLM outputs for "
                    "language mismatch metric which detects whether the language of "
                    "the input and output is the same."
                ),
            },
            BoolLeaderboard.METRIC_MODEL_FAILURES: {
                commons.MetricMeta.KEY_DISPLAY_NAME: "Language mismatch (fail)",
                commons.MetricMeta.KEY_DESCRIPTION: (
                    "Percentage of RAG/LLM outputs that failed to pass the evaluator "
                    "check for language mismatch metric which detects whether "
                    "the language of the input and output is the same."
                ),
            },
            BoolLeaderboard.METRIC_MODEL_RETRIEVAL_FAILURES: {
                commons.MetricMeta.KEY_DISPLAY_NAME: (
                    "Language mismatch retrieval failures"
                ),
                commons.MetricMeta.KEY_DESCRIPTION: (
                    "Percentage of RAG's retrieved contexts that failed to pass "
                    "the evaluator check for "
                    "language mismatch metric which detects whether the language of "
                    "the input and output is the same."
                ),
            },
            BoolLeaderboard.METRIC_MODEL_GENERATION_FAILURES: {
                commons.MetricMeta.KEY_DISPLAY_NAME: (
                    "Language mismatch generation failures"
                ),
                commons.MetricMeta.KEY_DESCRIPTION: (
                    "Percentage of outputs generated by RAG from the retrieved "
                    "contexts that failed to pass the evaluator check (equivalent to "
                    "the model failures) for language mismatch metric which detects "
                    "whether the language of the input and output is the same."
                ),
            },
            BoolLeaderboard.METRIC_MODEL_PARSE_FAILURES: {
                commons.MetricMeta.KEY_DISPLAY_NAME: (
                    "Language mismatch parsing failures"
                ),
                commons.MetricMeta.KEY_DESCRIPTION: (
                    "Percentage of RAG/LLM outputs that evaluator's judge "
                    "(LLM, RAG or model) was unable to parse, and therefore unable to "
                    "evaluate and provide a metrics score for "
                    "language mismatch metric which detects whether the language of "
                    "the input and output is the same."
                ),
            },
        }
    )

    _llm = True
    _rag = True

    _keywords = [
        evaluators.KEYWORD_LLM,
        evaluators.KEYWORD_EVALUATES_LLM,
        evaluators.KEYWORD_EVALUATES_RAG,
        evaluators.KEYWORD_RQ_P,
        evaluators.KEYWORD_RQ_AA,
        evaluators.KEYWORD_RQ_J,
        evaluators.KEYWORD_REQUIRES_OPENAI_KEY,
        evaluators.KEYWORD_SR_11_7_CS,
        evaluators.KEYWORD_SR_11_7_OA,
        evaluators.KEYWORD_NIST_AI_RMF_S,
        evaluators.KEYWORD_PROBLEM_TYPE_IR,
        evaluators.KEYWORD_PROBLEM_TYPE_SUM,
        evaluators.KEYWORD_PROBLEM_TYPE_QA,
        evaluators.KEYWORD_ES_GENERATE,
        evaluators.KEYWORD_METHOD_TYPE_NON_DETERMINISTIC,
        evaluators.KEYWORD_METHOD_JUDGE,
    ]

    _brief_description = """Language mismatch evaluator tries to determine whether
**the language** of the question (prompt/input) input and the actual answer is the same.

- LLM judge based language detection.
- Compatibility: RAG and LLM models."""
    _description = evaluators.Evaluator._description_builder(
        brief=f"""{_brief_description}

**Method**:

- The evaluator prompts the LLM judge to compare languages in the question and
  actual answer.
- Evaluator checks every test case. The result of the test case evaluation is a boolean.
- LLM models are compared based on the number of test cases where they succeeded.

Prompt used by the evaluator:

```
  You are examining the language of written text content.
  Here is the text:
  [BEGIN DATA]
  ************
  [QUESTION]: ```{{INPUT}}```
  [ANSWER]: ```{{ACTUAL_OUTPUT}}```
  ************
  [END DATA]
  Guess the language of the QUESTION and the language of the ANSWER.
  If the language of the QUESTION and the ANSWER is the same, respond using only
  "same". If the language of the QUESTION and the language of the ANSWER are
  different respond only using the word "different". Your response should be only
  one word without any explanation. Your task is only to consider the language
  not the semantics of the text. Different dialects of the same language as well as
  different tones within the same language are considered as the same language.
```
""",
        metrics_meta=_metrics_meta,
        keywords=_keywords,
        parameters=abc_byop_evaluator.AbcByopEvaluator._parameters,
        leaderboard_type=e10s.LlmBoolLeaderboardExplanation.explanation_type(),
    )

    def _initialize_prompt_template(self) -> str:
        return f"""You are examining the language of written text content.
    Here is the text:
    [BEGIN DATA]
    ************
    [QUESTION]: ```{abc_byop_evaluator.AbcByopEvaluator.IDENTIFIER_INPUT}```
    [ANSWER]: ```{abc_byop_evaluator.AbcByopEvaluator.IDENTIFIER_ACTUAL_OUTPUT}```
    ************
    [END DATA]
    Guess the language of the QUESTION and the language of the ANSWER.
    If the language of the QUESTION and the ANSWER is the same, respond using only
    "same". If the language of the QUESTION and the language of the ANSWER are
    different respond only using the word "different". Your response should be only
    one word without any explanation. Your task is only to consider the language
    not the semantics of the text. Different dialects of the same language as well as
    different tones within the same language are considered as the same language.
"""
