# Copyright 2017-2026 H2O.ai, Inc. All rights reserved.
from h2o_sonar.evaluators import rag_ragas_evaluator
from h2o_sonar.lib.api import commons
from h2o_sonar.lib.api import evaluators
from h2o_sonar.lib.api import explanations as e10s
from h2o_sonar.lib.api import formats as f5s
from h2o_sonar.lib.api import results


class AnswerRelevancyEvaluator(evaluators.Evaluator):
    _display_name = "Answer relevancy"
    _tagline = (
        "Evaluate actual answers based on question similarity to LLM-generated "
        "questions."
    )

    # COMPATIBILITY: LLM/RAG evaluation
    _rag = True
    _llm = False  # evaluator DOES require context

    # GLOBAL: metric value for all dataset rows
    _global_explanation = True
    # LOCAL: metric value for particular row
    _local_explanation = True
    _explanation_types = [
        e10s.LlmEvalResultsExplanation,
        e10s.LlmHeatmapLeaderboardExplanation,
        e10s.WorkDirArchiveExplanation,
    ]

    _keywords = [
        evaluators.KEYWORD_LLM,
        evaluators.KEYWORD_EVALUATES_RAG,
        evaluators.KEYWORD_RQ_P,
        evaluators.KEYWORD_RQ_RC,
        evaluators.KEYWORD_RQ_AA,
        evaluators.KEYWORD_RQ_J,
        evaluators.KEYWORD_REQUIRES_OPENAI_KEY,
        evaluators.KEYWORD_SR_11_7_CS,
        evaluators.KEYWORD_SR_11_7_OGA,
        evaluators.KEYWORD_SR_11_7_OA,
        evaluators.KEYWORD_NIST_AI_RMF_S,
        evaluators.KEYWORD_NIST_AI_RMF_AT,
        evaluators.KEYWORD_NIST_AI_RMF_VR,
        evaluators.KEYWORD_PROBLEM_TYPE_IR,
        evaluators.KEYWORD_PROBLEM_TYPE_QA,
        evaluators.KEYWORD_ES_GENERATE,
        evaluators.KEYWORD_METHOD_JUDGE,
        evaluators.KEYWORD_METHOD_TYPE_NON_DETERMINISTIC,
    ]

    _metrics_meta = commons.MetricsMeta(
        metrics=[
            commons.MetricMeta.clone(
                rag_ragas_evaluator.RagasEvaluator.METRIC_META_ANSWER_RELEVANCY
            )
        ]
    )

    _parameters = [
        evaluators.Evaluator._get_custom_param_metric_threshold(
            _metrics_meta.get_primary_metric()
        ),
        evaluators.Evaluator._PARAM_NAN_TOLERANCE,
        evaluators.Evaluator._PARAM_SAVE_LLM_RESULT,
        evaluators.Evaluator._PARAM_EVAL_JUDGE,
        evaluators.Evaluator._get_custom_param_min_test_case(),
    ]

    _modules_needed_by_name = ["ragas==0.1.3"]

    _brief_description = """Answer Relevancy evaluator is
assessing how pertinent the actual answer is to the given question. A lower score
indicates actual answer which is incomplete or contains redundant information.

- Mean cosine similarity of the original question and questions generated by
  the LLM judge.
- Compatibility: RAG and LLM evaluation.
- Based on
  [RAGAs library](https://docs.ragas.io/en/latest/concepts/metrics/index.html)"""
    _description = evaluators.Evaluator._description_builder(
        brief=f"""{_brief_description}

**Method**:

- The LLM judge is prompted to **generate an appropriate question** for
  the actual answer multiple times, and the **mean cosine similarity** of generated
  questions with the original question is measured.
- The score will range between `0` and `1` most of the time, but this is **not**
  mathematically guaranteed, due to the nature of the cosine similarity that ranging
  from `-1` to `1`.

```math
                    1   N
answer relevancy = ---  Σ cosine_similarity(emb(i-th question), emb(original question))
                    N  i=1
```

- Where:
     - `N` is the number of generated questions (3 by default).
     - `cosine_similarity` is the cosine similarity between the embeddings of the
       original question and the generated question.
     - `emb(i-th question)` is the embedding of the i-th question generated by LLM.
     - `emb(original question)` is the embedding of the original question.

See also:

- 3rd party metric documentation:
  https://docs.ragas.io/en/latest/concepts/metrics/index.html
- 3rd party library used: https://github.com/explodinggradients/ragas""",
        metrics_meta=_metrics_meta,
        keywords=_keywords,
        parameters=_parameters,
        leaderboard_type=e10s.LlmHeatmapLeaderboardExplanation.explanation_type(),
    )

    def __init__(self):
        evaluators.Evaluator.__init__(self)

        self.args = None
        self.problems = []
        self.log_name = "Answer relevancy"

        self.ragas = rag_ragas_evaluator.RagasEvaluator()

    def check_compatibility(
        self,
        params: commons.CommonInterpretationParams | None = None,
        **evaluator_params,
    ) -> bool:
        evaluators.Evaluator.check_compatibility(self, params, **evaluator_params)

        if not evaluators.Evaluator._check_llm_dataset_compatibility(
            self,
            params=params,
            evaluator_keywords=self.keywords,
            check_empty_contexts=evaluators.KEYWORD_RQ_RC in self.keywords,
            fail_on_all_empty_contexts=evaluators.KEYWORD_RQ_RC in self.keywords,
        ):
            return False

        # check that at least one row has actual answer
        if not self._check_llm_dataset_field_presence(
            params=params,
            require_actual_answer=True,
            require_expected_answer=False,
        ):
            return False

        return True

    def setup(self, model, persistence, **kwargs):
        evaluators.Evaluator.setup(self, model, persistence, **kwargs)

        self._resolve_evaluator_params()

        self.ragas.progress_callback = self.progress_callback
        self.ragas.setup(model, persistence, **kwargs)

    def evaluate(self, llm_testset, explanations_types=None, **kwargs) -> list:
        return self.ragas.eval_custom_metrics(
            llm_testset,
            metrics_threshold=self.args.get(
                evaluators.Evaluator.PARAM_METRIC_THRESHOLD,
                evaluators.Evaluator.DEFAULT_METRIC_THRESHOLD,
            ),
            save_llm_result=self.args.get(
                evaluators.Evaluator.PARAM_SAVE_LLM_RESULT,
                evaluators.Evaluator.DEFAULT_SAVE_LLM_RESULT,
            ),
            custom_eval_judge_cfg_key=self._resolve_judge_key(),
            metrics_to_run=AnswerRelevancyEvaluator._metrics_meta,
            evaluator=self,
            nan_tolerance=self.args.get(
                evaluators.Evaluator.PARAM_NAN_TOLERANCE,
                evaluators.Evaluator.DEFAULT_NAN_TOLERANCE,
            ),
        )

    # PROBLEMS: set by RAGAs evaluator on this evaluator instance
    # INSIGHTS: set by RAGAs evaluator on this evaluator instance

    def get_result(
        self,
    ) -> results.LeaderboardResult:
        return results.LeaderboardResult(
            persistence=self.persistence,
            explainer_id=AnswerRelevancyEvaluator.explainer_id(),
            h2o_sonar_config=self.config,
            logger=self.logger,
            explanation=e10s.LlmHeatmapLeaderboardExplanation,
            explanation_format=f5s.CustomJsonFormat,
        )
