# Copyright 2017-2026 H2O.ai, Inc. All rights reserved.
import traceback

import airium

from h2o_sonar import config as h2o_sonar_config
from h2o_sonar.lib.api import commons
from h2o_sonar.lib.api import datasets
from h2o_sonar.lib.api import evaluators
from h2o_sonar.lib.api import explanations as e10s
from h2o_sonar.lib.api import formats as f5s
from h2o_sonar.lib.api import models
from h2o_sonar.lib.api import problems
from h2o_sonar.lib.api import results
from h2o_sonar.utils import caching
from h2o_sonar.utils import progress as progress_utils
from h2o_sonar.utils import resource_mgmt
from h2o_sonar.utils import tokenization


try:
    import nltk

    HAS_NLTK = True
except ImportError:
    HAS_NLTK = False

try:
    import sentence_transformers

    HAS_SENTENCE_TRANSFORMERS = True
except ImportError:
    HAS_SENTENCE_TRANSFORMERS = False


class RagGroundednessEvaluator(evaluators.Evaluator):
    _display_name = "Groundedness (semantic similarity)"
    _tagline = (
        "Evaluate actual answers by assessing their relevance to the retrieved "
        "contexts."
    )

    METRIC_GROUNDEDNESS = "groundedness"

    _metrics_meta = commons.MetricsMeta(
        metrics=[
            commons.MetricMeta(
                key=METRIC_GROUNDEDNESS,
                display_name="Groundedness",
                description=(
                    "Groundedness metric determines whether the RAG outputs factually "
                    "correct information by comparing the **actual answer** sentences "
                    "to the retrieved **context** sentences."
                ),
                higher_is_better=True,
                threshold=evaluators.Evaluator.DEFAULT_METRIC_THRESHOLD,
                is_primary_metric=True,
            )
        ]
    )

    # COMPATIBILITY: LLM/RAG evaluation
    _rag = True

    # GLOBAL: metric value for all dataset rows
    _global_explanation = True
    # LOCAL: metric value for particular row
    _local_explanation = True
    _explanation_types = [
        e10s.LlmEvalResultsExplanation,
        e10s.LlmHeatmapLeaderboardExplanation,
        e10s.WorkDirArchiveExplanation,
    ]

    _parameters = [
        evaluators.Evaluator._get_custom_param_metric_threshold(
            _metrics_meta.get_primary_metric()
        ),
        evaluators.Evaluator._PARAM_SAVE_LLM_RESULT,
        evaluators.Evaluator._PARAM_SENTENCE_LEVEL_METRICS,
        evaluators.Evaluator._get_custom_param_min_test_case(),
    ]

    _keywords = [
        evaluators.KEYWORD_GPU_OPT,
        evaluators.KEYWORD_LLM,
        evaluators.KEYWORD_EVALUATES_RAG,
        evaluators.KEYWORD_RQ_RC,
        evaluators.KEYWORD_RQ_AA,
        evaluators.KEYWORD_SR_11_7_CS,
        evaluators.KEYWORD_SR_11_7_OA,
        evaluators.KEYWORD_NIST_AI_RMF_S,
        evaluators.KEYWORD_PROBLEM_TYPE_IR,
        evaluators.KEYWORD_PROBLEM_TYPE_QA,
        evaluators.KEYWORD_EVALUATOR_ROLE_REGULATOR,
        evaluators.KEYWORD_ES_GENERATE,
        evaluators.KEYWORD_METHOD_SEMANTIC_SIMILARITY,
        evaluators.KEYWORD_METHOD_TYPE_DETERMINISTIC,
        evaluators.KEYWORD_CAP_AH,
    ]

    _modules_needed_by_name = [
        h2o_sonar_config.DEP_SENTENCE_TRANSFORMERS,
        h2o_sonar_config.DEP_NLTK,
    ]

    _e_model_baai_bge = caching.MODEL_BAAI_BGE_SMALL_EN

    _brief_description = """Groundedness Evaluator assesses the groundedness of
the base **LLM model** in a Retrieval Augmented Generation (RAG) pipeline. It
evaluates whether the actual answer is factually correct information by **comparing**
the actual answer sentences to the retrieved context sentences - as the actual answer
generated by the LLM model **must be based on** the retrieved context."""
    _description = evaluators.Evaluator._description_builder(
        brief=f"""{_brief_description}

**Method**:

- The groundedness metric is calculated as:

```math
groundedness = min( {{ max( {{S(emb(a), emb(c)): for all c in C}} ): for all a in A }} )
```

- Where:
    - `A` is the actual answer.
    - `emb(a)` is a vector embedding of the actual answer sentence.
    - `C` is the context retrieved by the RAG model.
    - `emb(c)` is a vector embedding of the context chunk sentence.
    - `S(a, c)` is the 1 - cosine distance between the actual answer sentence `a`
      and the retrieved context sentence `c`.
- The evaluator uses **embeddings**
  [{_e_model_baai_bge}](https://huggingface.co/{_e_model_baai_bge}) (where BGE
  stands for "BAAI General Embedding" which refers to a suite of open-source text
  embedding models developed by the Beijing Academy of Artificial Intelligence (BAAI)).
""",
        metrics_meta=_metrics_meta,
        keywords=_keywords,
        parameters=_parameters,
        extra_insights=(
            "\n- The least grounded actual answer sentence (in case that "
            "the output metric score is below the threshold)."
        ),
        leaderboard_type=e10s.LlmHeatmapLeaderboardExplanation.explanation_type(),
    )

    COL_INPUT = datasets.LlmDataset.KEY_INPUT
    COL_CONTEXT = datasets.LlmDataset.KEY_CONTEXT
    COL_EXPECTED_OUTPUT = datasets.LlmDataset.KEY_EXPECTED_OUTPUT
    COL_ACTUAL_OUTPUT = datasets.LlmDataset.KEY_ACTUAL_OUTPUT
    COL_MODEL = "model"
    COL_SCORE = "score"

    def __init__(self):
        evaluators.Evaluator.__init__(self)

        self.args = None
        self.problems = []
        self.log_name = "RAG Groundedness"

    def check_compatibility(
        self,
        params: commons.CommonInterpretationParams | None = None,
        **evaluator_params,
    ) -> bool:
        evaluators.Evaluator.check_compatibility(self, params, **evaluator_params)

        if not HAS_SENTENCE_TRANSFORMERS:
            self.logger.error(
                self._check_compatibility_pckg_err_msg("sentence_transformers")
            )
            return False
        if not HAS_NLTK:
            self.logger.error(self._check_compatibility_pckg_err_msg("nltk"))
            return False

        if not evaluators.Evaluator._check_llm_dataset_compatibility(
            self,
            params=params,
            evaluator_keywords=self.keywords,
            check_empty_contexts=evaluators.KEYWORD_RQ_RC in self.keywords,
            fail_on_all_empty_contexts=evaluators.KEYWORD_RQ_RC in self.keywords,
        ):
            return False

        return True

    def setup(self, model, persistence, **kwargs):
        evaluators.Evaluator.setup(self, model, persistence, **kwargs)

        self._resolve_evaluator_params()
        caching.cache_nltk_punkt(self.logger)

    def evaluate(self, llm_testset, explanations_types=None, **kwargs) -> list:
        save_llm_result = self.args.get(
            evaluators.Evaluator.PARAM_SAVE_LLM_RESULT,
            evaluators.Evaluator.DEFAULT_SAVE_LLM_RESULT,
        )

        return self._evaluate(
            llm_testset=llm_testset,
            save_llm_result=save_llm_result,
        )

    # TODO rewrite this method as in Answer accuracy / BERTScore evaluators to 2 methods
    def _info_about_prompt_and_llm(self, row, html=None):
        key_2_evaluated_model = {m.key: m for m in self.models}
        if html is None:
            return (
                f'Additional details - prompt: "{row.i}", '
                f"LLM: {key_2_evaluated_model[row.model_key].llm_model_name}"
            )

        html("Additional details - prompt: ")
        with html.b():
            with html.i():
                html(f'"{row.i}"')
        html(", LLM: ")
        with html.code():
            html(key_2_evaluated_model[row.model_key].llm_model_name)

    def _evaluate(
        self,
        llm_testset,
        save_llm_result: bool,
    ) -> list:
        #
        # EVALUATION
        #

        key_2_evaluated_model = {m.key: m for m in self.models}

        # LLM host: RAG or service
        llm_host = (
            commons.LlmModelHostType.RAG
            if isinstance(
                next(iter(key_2_evaluated_model.values())), models.ExplainableRagModel
            )
            else commons.LlmModelHostType.SERVICE
        )

        eval_results = self._calculate_metrics(llm_testset=llm_testset)

        #
        # NORMALIZATION of the evaluation results to the common EXPLANATIONS/FORMAT(s)
        #

        # EXPLANATIONS
        explanations = []

        # EXPLANATION: all data (per prompt metrics)
        if save_llm_result:
            eval_results_explanation = e10s.LlmEvalResultsExplanation(
                evaluator=self,
                display_name="Evaluation metrics data",
                display_category=e10s.Explanation.DISPLAY_CAT_LLM,
                eval_results=eval_results,
            )
            # FORMATS of the explanation: JSon, CSV, DataTable
            eval_results_explanation.add_json_format()
            eval_results_explanation.add_csv_format()
            eval_results_explanation.add_datatable_format()
            explanations.append(eval_results_explanation)

        # THRESHOLD for the metric
        metrics_threshold = self.args.get(
            evaluators.Evaluator.PARAM_METRIC_THRESHOLD,
            evaluators.Evaluator.DEFAULT_METRIC_THRESHOLD,
        )
        self._metrics_meta.set_threshold(metrics_threshold)

        # EXPLANATION: heatmap leaderboard
        heatmap_explanation = e10s.LlmHeatmapLeaderboardExplanation.from_eval_results(
            evaluator=self,
            eval_results=eval_results,
            metrics_meta=self._metrics_meta,
            key_2_evaluated_model=key_2_evaluated_model,
            llm_host=llm_host,
            display_name="LLM heatmap leaderboard",
            display_category=e10s.GlobalSummaryFeatImpExplanation.DISPLAY_CAT_LLM,
            logger=self.logger,
        )
        heatmap_explanation.add_json_format(
            threshold=self.args.get(
                evaluators.Evaluator.PARAM_METRIC_THRESHOLD,
                self._metrics_meta.get_primary_metric().threshold,
            )
        )
        heatmap_explanation.add_markdown_format(
            sort_by_metric_id=self.METRIC_GROUNDEDNESS
        )
        heatmap_explanation.add_evalstudio_markdown_format(
            sort_by_metric_id=self.METRIC_GROUNDEDNESS
        )
        explanations.append(heatmap_explanation)

        # PROBLEMS for alerts and actionability
        self._diagnose_problems(
            eval_results=eval_results,
            key_2_evaluated_model=key_2_evaluated_model,
            leaderboard_explanation=heatmap_explanation,
        )

        # INSIGHTS
        self._diagnose_insights(leaderboard_explanation=heatmap_explanation)

        # EXPLANATION: HTML fragment
        if self.config and self.config.create_html_representations:
            try:
                html_explanation = e10s.GlobalHtmlFragmentExplanation(
                    evaluator=self,
                    display_name="LLM heatmap leaderboard as HTML",
                    display_category=e10s.Explanation.DISPLAY_CAT_COMPLIANCE,
                )
                html_explanation.add_html_format(
                    str(
                        heatmap_explanation.as_html(
                            sort_by_metric_id=self.METRIC_GROUNDEDNESS
                        )
                    ),
                )
                explanations.append(html_explanation)
            except Exception as ex:
                self.logger.warning(
                    f"{self.log_name}: HTML fragment explanation creation failed: "
                    f"{ex}\n{traceback.format_exc()}"
                )

        # EXPLANATION: ZIP archive of all artifacts created by the evaluator
        explanations.append(
            self.create_explanation_workdir_archive(
                display_name=f"Archive of {self._display_name} artifacts",
                display_category=e10s.Explanation.DISPLAY_CAT_COMPLIANCE,
            )
        )

        return explanations

    # Split docs into sentences
    @staticmethod
    def split_sentences(text: str) -> list[str]:
        """Split the data into sentences"""
        sentences = nltk.tokenize.sent_tokenize(text)
        sentences = [sent for sent in sentences if len(sent) > 10]
        return sentences

    def _calculate_groundedness(self, model, row):
        explanation_type = e10s.GlobalHtmlFragmentExplanation.explanation_type()

        context_embedded_sentences = []
        for c in row.context:
            try:
                context_embedded_sentences.append(model.encode(self.split_sentences(c)))
            except Exception as ex:
                d_prefix = (
                    "Error during vector embedding of the retrieved context chunk: "
                )
                description = (
                    f'{d_prefix}"{c}". {self._info_about_prompt_and_llm(row)}.'
                )
                self.logger.error(f"{description} - {ex}\n{traceback.format_exc()}")

                html = airium.Airium()
                html(d_prefix)
                with html.b():
                    with html.i():
                        html(f'"{c}"')
                html(".")
                self._info_about_prompt_and_llm(row, html)
                html(".")

                self.add_problem(
                    problems.ProblemAndAction(
                        description=description,
                        description_html=html,
                        evaluator_id=self.evaluator_id(),
                        problem_attrs={
                            problems.ProblemAndAction.ATTR_ROW_KEYS: [
                                (row.key, row.model_key)
                            ],
                            problems.ProblemAndAction.ATTR_TEST_CASE_KEYS: [row.key],
                            problems.ProblemAndAction.ATTR_EVALUATOR_NAME: (
                                self._display_name
                            ),
                        },
                        evaluator_name=self._display_name,
                        explanation_type=explanation_type,
                        explanation_name=e10s.GlobalHtmlFragmentExplanation.__name__,
                        explanation_mime=f5s.HtmlFormat.mime,
                        resources=[],
                    )
                )
                return float("NaN"), None
        output_sentences = self.split_sentences(row.actual_output)
        try:
            output_embedded_sentences = model.encode(output_sentences)
        except Exception as ex:
            d_prefix = "Error during vector embedding of the actual answer: "
            description = (
                f'{d_prefix}"{output_sentences}". '
                f"{self._info_about_prompt_and_llm(row)}."
            )
            self.logger.error(f"{description} - {ex}\n{traceback.format_exc()}")

            html = airium.Airium()
            html(d_prefix)
            with html.b():
                with html.i():
                    html(f'"{output_sentences}"')
            html(".")
            self._info_about_prompt_and_llm(row, html)
            html(".")

            self.add_problem(
                problems.ProblemAndAction(
                    description=description,
                    description_html=html,
                    evaluator_id=self.evaluator_id(),
                    problem_attrs={
                        problems.ProblemAndAction.ATTR_ROW_KEYS: [
                            (row.key, row.model_key)
                        ],
                        problems.ProblemAndAction.ATTR_TEST_CASE_KEYS: [row.key],
                        problems.ProblemAndAction.ATTR_EVALUATOR_NAME: (
                            self._display_name
                        ),
                    },
                    evaluator_name=self._display_name,
                    explanation_type=explanation_type,
                    explanation_name=e10s.GlobalHtmlFragmentExplanation.__name__,
                    explanation_mime=f5s.HtmlFormat.mime,
                    resources=[],
                )
            )
            return float("NaN"), None

        context_embedded_sentences = [
            ces for ces in context_embedded_sentences if len(ces) > 0
        ]

        if len(context_embedded_sentences) == 0 or len(output_embedded_sentences) == 0:
            d_prefix = (
                "Embedding of the context chunks or actual answer is empty - the "
                "evaluation dataset row will be skipped. "
            )
            description = f"{d_prefix}{self._info_about_prompt_and_llm(row)}."

            html = airium.Airium()
            html(d_prefix)
            self._info_about_prompt_and_llm(row, html)
            html(".")

            self.add_problem(
                problems.ProblemAndAction(
                    description=description,
                    description_html=html,
                    evaluator_id=self.evaluator_id(),
                    problem_attrs={
                        problems.ProblemAndAction.ATTR_ROW_KEYS: [
                            (row.key, row.model_key)
                        ],
                        problems.ProblemAndAction.ATTR_TEST_CASE_KEYS: [row.key],
                        problems.ProblemAndAction.ATTR_EVALUATOR_NAME: (
                            self._display_name
                        ),
                    },
                    evaluator_name=self._display_name,
                    explanation_type=explanation_type,
                    explanation_name=e10s.GlobalHtmlFragmentExplanation.__name__,
                    explanation_mime=f5s.HtmlFormat.mime,
                    resources=[],
                )
            )
            return float("NaN"), None

        sentence_groundedness = [
            max(
                1 - nltk.cluster.cosine_distance(sent, ctx_sent)
                for context_chunk in context_embedded_sentences
                for ctx_sent in context_chunk
            )
            for sent in output_embedded_sentences
        ]

        least_grounded_sentence_idx = min(
            range(len(sentence_groundedness)), key=lambda s: sentence_groundedness[s]
        )
        metric_result = sentence_groundedness[least_grounded_sentence_idx]

        threshold = self.args.get(
            evaluators.Evaluator.PARAM_METRIC_THRESHOLD,
            self._metrics_meta.get_primary_metric().threshold,
        )
        actual_output_meta = None
        if self.args.get(
            self.PARAM_SENTENCE_LEVEL_METRICS, self.DEFAULT_SENTENCE_LEVEL_METRICS
        ):
            all_actual_answer_sentences = nltk.sent_tokenize(row.actual_output)
            text_fragments = []
            for aa in all_actual_answer_sentences:
                try:
                    i = output_sentences.index(aa)
                    text_fragments.append(
                        tokenization.TextFragment(
                            text=aa,
                            metrics={
                                self.METRIC_GROUNDEDNESS: sentence_groundedness[i]
                            },
                            meta={},
                        )
                    )
                except ValueError:
                    # short sentence -> without metric
                    text_fragments.append(
                        tokenization.TextFragment(text=aa, metrics={}, meta={})
                    )

            actual_output_meta = tokenization.Tokenization(
                tokenization=tokenization.TOKENIZATION_TYPE_S_PUNKT, data=text_fragments
            )

        if metric_result < threshold:
            least_ground_sent = output_sentences[least_grounded_sentence_idx]

            d_prefix = (
                "The least grounded sentence identified by the Groundedness "
                "evaluator is: "
            )

            description = (
                f'{d_prefix}"{least_ground_sent}". '
                f"{self._info_about_prompt_and_llm(row)}."
            )

            html = airium.Airium()
            html(d_prefix)
            with html.b():
                with html.i():
                    html(f'"{least_ground_sent}"')
            html(".")
            self._info_about_prompt_and_llm(row, html)
            html(".")

            self.add_problem(
                problems.ProblemAndAction(
                    description=description,
                    description_html=html,
                    evaluator_id=self.evaluator_id(),
                    problem_code=problems.AVIDProblemCode.P0100_DATA,
                    problem_attrs={
                        problems.ProblemAndAction.ATTR_ROW_KEYS: [
                            (row.key, row.model_key)
                        ],
                        # input dataset ~ test lab ~ key is the test case key
                        problems.ProblemAndAction.ATTR_TEST_CASE_KEYS: [row.key],
                        problems.ProblemAndAction.ATTR_EVALUATOR_NAME: (
                            self._display_name
                        ),
                    },
                    evaluator_name=self._display_name,
                    explanation_type=explanation_type,
                    explanation_name=e10s.GlobalHtmlFragmentExplanation.__name__,
                    explanation_mime=f5s.HtmlFormat.mime,
                    resources=[],
                )
            )

        return metric_result, actual_output_meta

    def _calculate_metrics(self, llm_testset):
        llm_dataset = datasets.LlmDataset.from_datatable_dict(llm_testset.to_dict())

        # evaluator runs only ONE metric at a time
        self.report_progress(0.01, "Configuring metrics...")

        eval_results = datasets.LlmEvalResults()

        device = h2o_sonar_config.config.resolve_gpu_cpu_device(result_format="str")
        with resource_mgmt.PytorchModelLifeCycleManager(
            sentence_transformers.SentenceTransformer(
                RagGroundednessEvaluator._e_model_baai_bge,
                device=device,
                revision=caching.REVISIONS_FOR_MODEL.get(
                    RagGroundednessEvaluator._e_model_baai_bge, "main"
                ),
            )
        ) as embedding_model:
            # for every test case run metric (row by row)
            for e, r in enumerate(llm_dataset.inputs):
                # progress
                self.report_progress(
                    progress=progress_utils.ProgressCallbackContext.progress_for_steps(
                        e + 1, len(llm_dataset.inputs)
                    ),
                    message=evaluators.Evaluator._eval_row_progress_msg(
                        metric_name=self.METRIC_GROUNDEDNESS,
                        device=device,
                        row=e + 1,
                        total_rows=len(llm_dataset.inputs),
                    ),
                )

                # handle actual answer retrieval error ~ RAG/LLM client crash
                if evaluators.Evaluator._is_internal_err_answer(r.actual_output):
                    # set WORST metrics values
                    eval_results.add_result(
                        datasets.LlmEvalResults.LlmEvalResultRow(
                            dataset_row=r,
                            metrics={
                                self.METRIC_GROUNDEDNESS: 0.0,
                            },
                        )
                    )
                    continue

                result, result_tokenization = self._calculate_groundedness(
                    embedding_model, r
                )
                if result == result:  # not NaN
                    eval_results.add_result(
                        datasets.LlmEvalResults.LlmEvalResultRow(
                            dataset_row=r,
                            metrics={self.METRIC_GROUNDEDNESS: result},
                            actual_output_meta=(
                                [result_tokenization] if result_tokenization else []
                            ),
                        )
                    )

        return eval_results

    def _diagnose_problems(
        self,
        eval_results: datasets.LlmEvalResults,
        key_2_evaluated_model: dict,
        leaderboard_explanation: e10s.LlmHeatmapLeaderboardExplanation,
    ):
        # perturbation flips
        self._diagnose_perturbation_problems(
            eval_results=eval_results,
            key_2_evaluated_model=key_2_evaluated_model,
        )

        # threshold failures
        problems.problems_for_heat_leaderboard(
            evaluator=self,
            leaderboard=leaderboard_explanation,
            metric_threshold=self.args.get(
                evaluators.Evaluator.PARAM_METRIC_THRESHOLD,
                self._metrics_meta.get_primary_metric().threshold,
            ),
            primary_metric_meta=self._metrics_meta.get_primary_metric(),
            problem_type="accuracy",
            actions_description=(
                "Focus on three areas: training data, grounding techniques, and "
                "factual consistency checks. First, curating training data to include "
                "reliable sources and diverse perspectives can minimize exposure to "
                "factual inaccuracies. Second, incorporating grounding techniques "
                "like entity verification and external knowledge bases can help "
                "the model anchor its responses in real-world information. Finally, "
                "implementing factual consistency checks during generation, such "
                "as cross-referencing with knowledge bases or reliable sources, "
                "can help identify and flag potential hallucinations before they "
                "reach the user. This three-pronged approach can significantly "
                "reduce the presence of hallucinations in RAG model outputs."
            ),
            explanation_type=e10s.GlobalHtmlFragmentExplanation.explanation_type(),
            explanation_name=e10s.GlobalHtmlFragmentExplanation.__name__,
            explanation_mime=f5s.HtmlFormat.mime,
        )

    def _diagnose_insights(
        self, leaderboard_explanation: e10s.LlmHeatmapLeaderboardExplanation
    ):
        t_html_fragment = e10s.GlobalHtmlFragmentExplanation

        leaderboard_explanation.get_insights(
            metrics_meta=self._metrics_meta,
            metric_name_protection=True,
            extra_description_worst=(
                "Focus on three areas: training data, grounding techniques, and "
                "factual consistency checks. First, curating training data to include "
                "reliable sources and diverse perspectives can minimize exposure to "
                "factual inaccuracies. Second, incorporating grounding techniques "
                "like entity verification and external knowledge bases can help "
                "the model anchor its responses in real-world information. Finally, "
                "implementing factual consistency checks during generation, such "
                "as cross-referencing with knowledge bases or reliable sources, "
                "can help identify and flag potential hallucinations before they "
                "reach the user. This three-pronged approach can significantly "
                "reduce the presence of hallucinations in RAG model outputs."
            ),
            insight_type="accuracy",
            explanation_type=t_html_fragment.explanation_type(),
            explanation_name=t_html_fragment.__name__,
            explanation_mime=f5s.HtmlFormat.mime,
        )

    def get_result(
        self,
    ) -> results.LeaderboardResult:
        return results.LeaderboardResult(
            persistence=self.persistence,
            explainer_id=RagGroundednessEvaluator.explainer_id(),
            h2o_sonar_config=self.config,
            logger=self.logger,
            explanation=e10s.LlmHeatmapLeaderboardExplanation,
            explanation_format=f5s.CustomJsonFormat,
        )
