# Copyright 2018-2026 H2O.ai, Inc. All rights reserved.
from h2o_sonar.evaluators import abc_byop_evaluator
from h2o_sonar.lib.api import commons
from h2o_sonar.lib.api import evaluators
from h2o_sonar.lib.api import explanations as e10s
from h2o_sonar.lib.api import problems


# aliases
BoolLeaderboard = e10s.LlmBoolLeaderboardExplanation


class SummarizationByopEvaluator(abc_byop_evaluator.AbcByopEvaluator):
    _display_name = "Summarization (judge)"
    _tagline = "Evaluate summary quality using an LLM and reference summary."

    _CLASSES = abc_byop_evaluator.AbcByopEvaluator.Classes(
        failure="bad", success="good"
    )

    _PROBLEM_THRESHOLD_PROTO = problems.ProblemAndAction(
        description="",
        problem_type="summarization",
        problem_code=problems.AVIDProblemCode.P0200_MODEL,
        actions_description=(
            "To improve summarizations, focus on three key areas:  refinement, "
            "evaluation, and training data. The LLM can be equipped with "
            "auto-refinement modules that assess its own summaries and identify "
            "areas for improvement, like missing key points. Additionally, "
            "using metrics that go beyond surface-level similarity to human-written "
            "summaries can guide the training process. Finally, incorporating diverse "
            "and high-quality summaries into the training data provides the "
            "LLM with better examples to learn from, leading to more comprehensive "
            "and informative summaries."
        ),
        severity=problems.ProblemSeverity.medium,
    )

    _metrics_meta = BoolLeaderboard.LEADERBOARD_METRICS_META.copy_with_overrides(
        {
            BoolLeaderboard.METRIC_MODEL_PASSES: {
                commons.MetricMeta.KEY_DISPLAY_NAME: "Good summary (pass)",
                commons.MetricMeta.KEY_DESCRIPTION: (
                    "Percentage of successfully evaluated RAG/LLM outputs for "
                    "summarization quality metrics which uses a language model judge "
                    "to determine whether the summary is correct or not."
                ),
            },
            BoolLeaderboard.METRIC_MODEL_FAILURES: {
                commons.MetricMeta.KEY_DISPLAY_NAME: "Bad summary (fail)",
                commons.MetricMeta.KEY_DESCRIPTION: (
                    "Percentage of RAG/LLM outputs that failed to pass the evaluator "
                    "check for summarization quality metrics which uses a language "
                    "model judge to determine whether the summary is correct or not."
                ),
            },
            BoolLeaderboard.METRIC_MODEL_RETRIEVAL_FAILURES: {
                commons.MetricMeta.KEY_DISPLAY_NAME: (
                    "Summarization retrieval failures"
                ),
                commons.MetricMeta.KEY_DESCRIPTION: (
                    "Percentage of RAG's retrieved contexts that failed to pass "
                    "the evaluator check for summarization quality metrics which uses "
                    "a language model judge to determine whether the summary is "
                    "correct or not."
                ),
            },
            BoolLeaderboard.METRIC_MODEL_GENERATION_FAILURES: {
                commons.MetricMeta.KEY_DISPLAY_NAME: (
                    "Summarization generation failures"
                ),
                commons.MetricMeta.KEY_DESCRIPTION: (
                    "Percentage of outputs generated by RAG from the retrieved "
                    "contexts that failed to pass the evaluator check (equivalent to "
                    "the model failures) for summarization quality metrics which uses "
                    "a language model judge to determine whether the summary is "
                    "correct or not."
                ),
            },
            BoolLeaderboard.METRIC_MODEL_PARSE_FAILURES: {
                commons.MetricMeta.KEY_DISPLAY_NAME: "Summarization parsing failures",
                commons.MetricMeta.KEY_DESCRIPTION: (
                    "Percentage of RAG/LLM outputs that evaluator's judge "
                    "(LLM, RAG or model) was unable to parse, and therefore unable to "
                    "evaluate and provide a metrics score for summarization quality "
                    "metrics which uses a language model judge to determine whether "
                    "the summary is correct or not."
                ),
            },
        }
    )

    _llm = True
    _rag = True

    _keywords = [
        evaluators.KEYWORD_LLM,
        evaluators.KEYWORD_EVALUATES_LLM,
        evaluators.KEYWORD_EVALUATES_RAG,
        evaluators.KEYWORD_RQ_P,
        evaluators.KEYWORD_RQ_EA,
        evaluators.KEYWORD_RQ_AA,
        evaluators.KEYWORD_RQ_J,
        evaluators.KEYWORD_REQUIRES_OPENAI_KEY,
        evaluators.KEYWORD_SR_11_7_CS,
        evaluators.KEYWORD_SR_11_7_OA,
        evaluators.KEYWORD_NIST_AI_RMF_S,
        evaluators.KEYWORD_PROBLEM_TYPE_IR,
        evaluators.KEYWORD_PROBLEM_TYPE_QA,
        evaluators.KEYWORD_PROBLEM_TYPE_SUM,  # reference summary NOT required
        evaluators.KEYWORD_ES_SUMMARIZE,
        evaluators.KEYWORD_METHOD_TYPE_NON_DETERMINISTIC,
        evaluators.KEYWORD_METHOD_JUDGE,
    ]

    _brief_description = """Summarization evaluator uses an LLM judge to assess
the quality of the summary made by the evaluated model using **a reference summary**.

- LLM judge based summarization evaluation.
- Requires a reference summary.
- Compatibility: RAG and LLM models."""
    _description = evaluators.Evaluator._description_builder(
        brief=f"""{_brief_description}

**Method**:

- The evaluator prompts the LLM judge to compare in the actual answer
  (evaluated RAG/LLM summary) and expected answer (reference summary).
- Evaluator checks every test case for the presence of the contact information.
  The result of the test case evaluation is a boolean.
- LLM models are compared based on the number of test cases where they succeeded.

Prompt used by the evaluator:

```
  You are comparing the summary text and it's original document and
  trying to determine if the summary is good. Here is the data:
      [BEGIN DATA]
      ************
      [Summary]: {{ACTUAL_OUTPUT}}
      ************
      [Original Document]: {{INPUT}}
      [END DATA]
  Compare the Summary above to the Original Document and determine if the Summary is
  comprehensive, concise, coherent, and independent relative to the Original Document.
  Your response must be a single word, either "good" or "bad", and should not contain
  any text or characters aside from that. "bad" means that the Summary is not
  comprehensive, concise, coherent, and independent relative to the Original Document.
  "good" means the Summary is comprehensive, concise, coherent, and independent relative
  to the Original Document.
```
""",
        metrics_meta=_metrics_meta,
        keywords=_keywords,
        parameters=abc_byop_evaluator.AbcByopEvaluator._parameters,
        leaderboard_type=e10s.LlmBoolLeaderboardExplanation.explanation_type(),
    )

    def _initialize_prompt_template(self) -> str:
        return f"""You are comparing the summary text and it's original document and
trying to determine if the summary is good. Here is the data:
    [BEGIN DATA]
    ************
    [Summary]: {abc_byop_evaluator.AbcByopEvaluator.IDENTIFIER_ACTUAL_OUTPUT}
    ************
    [Original Document]: {abc_byop_evaluator.AbcByopEvaluator.IDENTIFIER_INPUT}
    [END DATA]
Compare the Summary above to the Original Document and determine if the Summary is
comprehensive, concise, coherent, and independent relative to the Original Document.
Your response must be a single word, either "good" or "bad", and should not contain any
text or characters aside from that. "bad" means that the Summary is not comprehensive,
concise, coherent, and independent relative to the Original Document. "good" means the
Summary is comprehensive, concise, coherent, and independent relative to the Original
Document.
"""
