# Copyright 2018-2026 H2O.ai, Inc. All rights reserved.
import airium


def html_svg_h2oai_logo(html: airium.Airium):
    """Inject H2O.ai SVG logo to HTML.

    Parameters
    ----------
    html : airium.Airium
      Airium HTML instance.

    """

    with html.svg(
        height="40",
        id="Layer_1",
        viewbox="0 0 600.28 600.28",
        width="40",
        xmlns="http://www.w3.org/2000/svg",
        **{"data-name": "Layer 1"},
    ):
        with html.defs():
            with html.style():
                html(".cls-1{fill:#fec925;}.cls-2{fill:#161616;}.cls-3{fill:#54585a;}")
        with html.g(id="Fill-1"):
            html.rect(klass="cls-1", height="600.28", rx="23.24", width="600.28")
        html.path(
            klass="cls-2",
            d=(
                "M174.33,246.06v92.78H152.86v-38H110.71v38H89"
                ".24V246.06h21.47v36.58h42.15V246.06Z"
            ),
        )
        html.path(
            klass="cls-2",
            d=(
                "M259.81,321.34v17.5H189.7V324.92l35.78-33.8c8.22-7.82,9.68-12.59,"
                "9.68-17.09,0-7.29-5-11.53-14.85-11.53-7.95,0-14.71,3-19.21,"
                "9.27L185.46,261.7c7.15-10.47,20.14-17.23,36.84-17.23,20.68,0,"
                "34.46,10.6,34.46,27.44,0,9-2.52,17.22-15.51,29.29l-21.33,20.14Z"
            ),
        )
        html.path(
            klass="cls-2",
            d=(
                "M268.69,292.45c0-27.57,21.47-48,50.76-48s50.76,20.28,50.76,"
                "48-21.6,48-50.76,48S268.69,320,268.69,292.45Zm79.78,"
                "0c0-17.63-12.46-29.69-29-29.69s-29,12.06-29,29.69,12.46,29.69,29,"
                "29.69S348.47,310.08,348.47,292.45Z"
            ),
        )
        html.path(
            klass="cls-3",
            d=(
                "M377.23,326.91c0-7.69,5.7-12.73,12.85-12.73s12.86,5,12.86,"
                "12.73a12.86,12.86,0,1,1-25.71,0Z"
            ),
        )
        html.path(
            klass="cls-3",
            d=(
                "M481.4,298.15v40.69H462.05V330c-3.84,6.49-11.27,9.94-21.74,"
                "9.94-16.7,0-26.64-9.28-26.64-21.61,0-12.59,8.88-21.34,"
                "30.62-21.34h16.43c0-8.87-5.3-14-16.43-14-7.55,0-15.37,"
                "2.51-20.54,6.62l-7.43-14.44c7.82-5.57,19.35-8.62,"
                "30.75-8.62C468.81,266.47,481.4,276.54,481.4,298.15Zm-20.68,"
                "18.16V309H446.54c-9.67,0-12.72,3.57-12.72,8.35,0,5.16,4.37,"
                "8.61,11.66,8.61C452.37,326,458.34,322.8,460.72,316.31Z"
            ),
        )
        html.path(
            klass="cls-3",
            d=(
                "M497.56,246.06c0-6.49,5.17-11.53,12.86-11.53s12.86,4.77,12.86,"
                "11.13c0,6.89-5.17,11.93-12.86,11.93S497.56,252.55,497.56,"
                "246.06Zm2.52,21.47h20.68v71.31H500.08Z"
            ),
        )


def evaluation_report_html_head(a: airium.Airium, title: str = "H2O Sonar"):
    """Create head of HTML representation.

    Parameters
    ----------
    a : airium.Airium
      Airium HTML instance.
    title : str
      Optional HTML head title.

    """

    with a.head():
        a.meta(content="text/html; charset=UTF-8", **{"http-equiv": "Content-Type"})
        a.meta(content="width=device-width, initial-scale=1", name="viewport")
        with a.style():
            a(
                "/* W3.CSS 4.15 December 2020 by Jan Egil and Borge Refsnes */"
                "\n      html{box-sizing:border-box}*,*:before,*:after{box-sizing"
                ":inherit}\n      /* Extract from normalize.css by Nicolas Gallag"
                "her and Jonathan Neal git.io/normalize */\n      html{-ms-text-s"
                "ize-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}\n  "
                "    article,aside,details,figcaption,figure,footer,header,main,m"
                "enu,nav,section{display:block}summary{display:list-item}\n      "
                "audio,canvas,progress,video{display:inline-block}progress{vertic"
                "al-align:baseline}\n      audio:not([controls]){display:none;hei"
                "ght:0}[hidden],template{display:none}\n      a{background-color:"
                "transparent}a:active,a:hover{outline-width:0}\n      abbr[title]"
                "{border-bottom:none;text-decoration:underline;text-decoration:un"
                "derline dotted}\n      b,strong{font-weight:bolder}dfn{font-styl"
                "e:italic}mark{background:#ff0;color:#000}\n      small{font-size"
                ":80%}sub,sup{font-size:75%;line-height:0;position:relative;verti"
                "cal-align:baseline}\n      sub{bottom:-0.25em}sup{top:-0.5em}fig"
                "ure{margin:1em 40px}img{border-style:none}\n      code,kbd,pre,s"
                "amp{font-family:monospace,monospace;font-size:1em}hr{box-sizing:"
                "content-box;height:0;overflow:visible}\n      button,input,selec"
                "t,textarea,optgroup{font:inherit;margin:0}optgroup{font-weight:b"
                "old}\n      button,input{overflow:visible}button,select{text-tra"
                "nsform:none}\n      button,[type=button],[type=reset],[type=subm"
                "it]{-webkit-appearance:button}\n      button::-moz-focus-inner,["
                "type=button]::-moz-focus-inner,[type=reset]::-moz-focus-inner,[t"
                "ype=submit]::-moz-focus-inner{border-style:none;padding:0}\n    "
                "  button:-moz-focusring,[type=button]:-moz-focusring,[type=reset"
                "]:-moz-focusring,[type=submit]:-moz-focusring{outline:1px dotted"
                " ButtonText}\n      fieldset{border:1px solid #c0c0c0;margin:0 2"
                "px;padding:.35em .625em .75em}\n      legend{color:inherit;displ"
                "ay:table;max-width:100%;padding:0;white-space:normal}textarea{ov"
                "erflow:auto}\n      [type=checkbox],[type=radio]{padding:0}\n   "
                "   [type=number]::-webkit-inner-spin-button,[type=number]::-webk"
                "it-outer-spin-button{height:auto}\n      [type=search]{-webkit-a"
                "ppearance:textfield;outline-offset:-2px}\n      [type=search]::-"
                "webkit-search-decoration{-webkit-appearance:none}\n      ::-webk"
                "it-file-upload-button{-webkit-appearance:button;font:inherit}\n "
                "     /* End extract */\n      html,body{font-family:Verdana,sans"
                "-serif;font-size:15px;line-height:1.5}html{overflow-x:hidden}\n "
                "     h1{font-size:36px}h2{font-size:30px}h3{font-size:24px}h4{fo"
                "nt-size:20px}h5{font-size:18px}h6{font-size:16px}\n      .w3-ser"
                "if{font-family:serif}.w3-sans-serif{font-family:sans-serif}.w3-c"
                "ursive{font-family:cursive}.w3-monospace{font-family:monospace}"
                '\n      h1,h2,h3,h4,h5,h6{font-family:"Segoe UI",Arial,sans-seri'
                "f;font-weight:400;margin:10px 0}.w3-wide{letter-spacing:4px}\n  "
                "    hr{border:0;border-top:1px solid #eee;margin:20px 0}\n      "
                ".w3-image{max-width:100%;height:auto}img{vertical-align:middle}a"
                "{color:inherit}\n      .w3-table,.w3-table-all{border-collapse:c"
                "ollapse;border-spacing:0;width:100%;display:table}.w3-table-all{"
                "border:1px solid #ccc}\n      .w3-bordered tr,.w3-table-all tr{b"
                "order-bottom:1px solid #ddd}.w3-striped tbody tr:nth-child(even)"
                "{background-color:#f1f1f1}\n      .w3-table-all tr:nth-child(odd"
                "){background-color:#fff}.w3-table-all tr:nth-child(even){backgro"
                "und-color:#f1f1f1}\n      .w3-hoverable tbody tr:hover,.w3-ul.w3"
                "-hoverable li:hover{background-color:#ccc}.w3-centered tr th,.w3"
                "-centered tr td{text-align:center}\n      .w3-table td,.w3-table"
                " th,.w3-table-all td,.w3-table-all th{padding:8px 8px;display:ta"
                "ble-cell;text-align:left;vertical-align:top}\n      .w3-table th"
                ":first-child,.w3-table td:first-child,.w3-table-all th:first-chi"
                "ld,.w3-table-all td:first-child{padding-left:16px}\n      .w3-bt"
                "n,.w3-button{border:none;display:inline-block;padding:8px 16px;v"
                "ertical-align:middle;overflow:hidden;text-decoration:none;color:"
                "inherit;background-color:inherit;text-align:center;cursor:pointe"
                "r;white-space:nowrap}\n      .w3-btn:hover{box-shadow:0 8px 16px"
                " 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19)}\n      .w3-btn"
                ",.w3-button{-webkit-touch-callout:none;-webkit-user-select:none;"
                "-khtml-user-select:none;-moz-user-select:none;-ms-user-select:no"
                "ne;user-select:none}   \n      .w3-disabled,.w3-btn:disabled,.w3"
                "-button:disabled{cursor:not-allowed;opacity:0.3}.w3-disabled *,"
                ":disabled *{pointer-events:none}\n      "
                ".w3-btn.w3-disabled:hover,.w3-btn:disabled:hover{"
                "box-shadow:none}\n      .w3-badge,.w3-tag{"
                "background-color:#000;color:#fff;display:inline-block;padding"
                "-left:8px;padding-right:8px;text-align:center}.w3-badge{"
                "border-radius:50%}\n      .w3-ul{"
                "list-style-type:none;padding:0;margin:0}.w3-ul li{padding:8px "
                "16px;border-bottom:1px solid #ddd}.w3-ul li:last-child{"
                "border-bottom:none}\n      .w3-tooltip,.w3-display-container{"
                "position:relative}.w3-tooltip .w3-text{"
                "display:none}.w3-tooltip:hover .w3-text{display:inline-block}\n  "
                "    .w3-ripple:active{opacity:0.5}.w3-ripple{transition:opacity "
                "0s}\n      .w3-input{"
                "padding:8px;display:block;border:none;border-bottom:1px solid "
                "#ccc;width:100%}\n      .w3-select{padding:9px "
                "0;width:100%;border:none;border-bottom:1px solid #ccc}\n      "
                ".w3-dropdown-click,.w3-dropdown-hover{"
                "position:relative;display:inline-block;cursor:pointer}\n      "
                ".w3-dropdown-hover:hover .w3-dropdown-content{display:block}\n   "
                "   .w3-dropdown-hover:first-child,.w3-dropdown-click:hover{"
                "background-color:#ccc;color:#000}\n      "
                ".w3-dropdown-hover:hover > .w3-button:first-child,"
                ".w3-dropdown-click:hover > .w3-button:first-child{"
                "background-color:#ccc;color:#000}\n      .w3-dropdown-content{"
                "cursor:auto;color:#000;background-color:#fff;display:none"
                ";position:absolute;min-width:160px;margin:0;padding:0;z-index:1"
                "}\n      .w3-check,.w3-radio{"
                "width:24px;height:24px;position:relative;top:6px}\n      "
                ".w3-sidebar{"
                "height:100%;width:200px;background-color:#fff;position:fixed"
                "!important;z-index:1;overflow:auto}\n      .w3-bar-block "
                ".w3-dropdown-hover,.w3-bar-block .w3-dropdown-click{"
                "width:100%}\n      .w3-bar-block .w3-dropdown-hover "
                ".w3-dropdown-content,.w3-bar-block .w3-dropdown-click "
                ".w3-dropdown-content{min-width:100%}\n      .w3-bar-block "
                ".w3-dropdown-hover .w3-button,.w3-bar-block .w3-dropdown-click "
                ".w3-button{width:100%;text-align:left;padding:8px 16px}\n      "
                ".w3-main,#main{transition:margin-left .4s}\n      .w3-modal{"
                "z-index:3;display:none;padding-top:100px;position:fixed;left:0"
                ";top:0;width:100%;height:100%;overflow:auto;background-color"
                ":rgb(0,0,0);background-color:rgba(0,0,0,0.4)}\n      "
                ".w3-modal-content{"
                "margin:auto;background-color:#fff;position:relative;padding:0"
                ";outline:0;width:600px}\n      .w3-bar{"
                "width:100%;overflow:hidden}.w3-center .w3-bar{"
                "display:inline-block;width:auto}\n      .w3-bar .w3-bar-item{"
                "padding:8px 16px;float:left;width:auto;border:none;display:block"
                ";outline:0}\n      .w3-bar .w3-dropdown-hover,.w3-bar "
                ".w3-dropdown-click{position:static;float:left}\n      .w3-bar "
                ".w3-button{white-space:normal}\n      .w3-bar-block "
                ".w3-bar-item{width:100%;display:block;padding:8px "
                "16px;text-align:left;border:none;white-space:normal;float:none"
                ";outline:0}\n      .w3-bar-block.w3-center .w3-bar-item{"
                "text-align:center}.w3-block{display:block;width:100%}\n      "
                ".w3-responsive{display:block;overflow-x:auto}\n      "
                ".w3-container:after,.w3-container:before,.w3-panel:after,"
                ".w3-panel:before,.w3-row:after,.w3-row:before,"
                ".w3-row-padding:after,.w3-row-padding:before,\n      "
                ".w3-cell-row:before,.w3-cell-row:after,.w3-clear:after,"
                ".w3-clear:before,.w3-bar:before,.w3-bar:after{"
                'content:"";display:table;clear:both}\n      .w3-col,.w3-half,'
                ".w3-third,.w3-twothird,.w3-threequarter,.w3-quarter{"
                "float:left;width:100%}\n      .w3-col.s1{"
                "width:8.33333%}.w3-col.s2{width:16.66666%}.w3-col.s3{"
                "width:24.99999%}.w3-col.s4{width:33.33333%}\n      .w3-col.s5{"
                "width:41.66666%}.w3-col.s6{width:49.99999%}.w3-col.s7{"
                "width:58.33333%}.w3-col.s8{width:66.66666%}\n      .w3-col.s9{"
                "width:74.99999%}.w3-col.s10{width:83.33333%}.w3-col.s11{"
                "width:91.66666%}.w3-col.s12{width:99.99999%}\n      @media ("
                "min-width:601px){.w3-col.m1{width:8.33333%}.w3-col.m2{"
                "width:16.66666%}.w3-col.m3,.w3-quarter{"
                "width:24.99999%}.w3-col.m4,.w3-third{width:33.33333%}\n\t\t\t    "
                "   .w3-col.m5{width:41.66666%}.w3-col.m6,.w3-half{"
                "width:49.99999%}.w3-col.m7{width:58.33333%}.w3-col.m8,"
                ".w3-twothird{width:66.66666%}\n\t\t\t       .w3-col.m9,"
                ".w3-threequarter{width:74.99999%}.w3-col.m10{"
                "width:83.33333%}.w3-col.m11{width:91.66666%}.w3-col.m12{"
                "width:99.99999%}}\n      @media (min-width:993px){.w3-col.l1{"
                "width:8.33333%}.w3-col.l2{width:16.66666%}.w3-col.l3{"
                "width:24.99999%}.w3-col.l4{width:33.33333%}\n\t\t\t       "
                ".w3-col.l5{width:41.66666%}.w3-col.l6{"
                "width:49.99999%}.w3-col.l7{width:58.33333%}.w3-col.l8{"
                "width:66.66666%}\n\t\t\t       .w3-col.l9{"
                "width:74.99999%}.w3-col.l10{width:83.33333%}.w3-col.l11{"
                "width:91.66666%}.w3-col.l12{width:99.99999%}}\n      .w3-rest{"
                "overflow:hidden}.w3-stretch{"
                "margin-left:-16px;margin-right:-16px}\n      .w3-content,"
                ".w3-auto{margin-left:auto;margin-right:auto}.w3-content{"
                "max-width:980px}.w3-auto{max-width:1140px}\n      .w3-cell-row{"
                "display:table;width:100%}.w3-cell{display:table-cell}\n      "
                ".w3-cell-top{vertical-align:top}.w3-cell-middle{"
                "vertical-align:middle}.w3-cell-bottom{vertical-align:bottom}\n   "
                "   .w3-hide{display:none!important}.w3-show-block,.w3-show{"
                "display:block!important}.w3-show-inline-block{"
                "display:inline-block!important}\n      @media ("
                "max-width:1205px){.w3-auto{max-width:95%}}\n      @media ("
                "max-width:600px){.w3-modal-content{margin:0 "
                "10px;width:auto!important}.w3-modal{padding-top:30px}\n\t\t\t    "
                "   .w3-dropdown-hover.w3-mobile .w3-dropdown-content,"
                ".w3-dropdown-click.w3-mobile .w3-dropdown-content{"
                "position:relative}\t\n\t\t\t       .w3-hide-small{"
                "display:none!important}.w3-mobile{"
                "display:block;width:100%!important}.w3-bar-item.w3-mobile,"
                ".w3-dropdown-hover.w3-mobile,.w3-dropdown-click.w3-mobile{"
                "text-align:center}\n\t\t\t       .w3-dropdown-hover.w3-mobile,"
                ".w3-dropdown-hover.w3-mobile .w3-btn,"
                ".w3-dropdown-hover.w3-mobile .w3-button,"
                ".w3-dropdown-click.w3-mobile,.w3-dropdown-click.w3-mobile "
                ".w3-btn,.w3-dropdown-click.w3-mobile .w3-button{width:100%}}\n   "
                "   @media (max-width:768px){.w3-modal-content{"
                "width:500px}.w3-modal{padding-top:50px}}\n      @media ("
                "min-width:993px){.w3-modal-content{width:900px}.w3-hide-large{"
                "display:none!important}.w3-sidebar.w3-collapse{"
                "display:block!important}}\n      @media (max-width:992px) and ("
                "min-width:601px){.w3-hide-medium{display:none!important}}\n      "
                "@media (max-width:992px){.w3-sidebar.w3-collapse{"
                "display:none}.w3-main{"
                "margin-left:0!important;margin-right:0!important}.w3-auto{"
                "max-width:100%}}\n      .w3-top,.w3-bottom{"
                "position:fixed;width:100%;z-index:1}.w3-top{top:0}.w3-bottom{"
                "bottom:0}\n      .w3-overlay{"
                "position:fixed;display:none;width:100%;height:100%;top:0;left:0"
                ";right:0;bottom:0;background-color:rgba(0,0,0,0.5);z-index:2}\n  "
                "    .w3-display-topleft{"
                "position:absolute;left:0;top:0}.w3-display-topright{"
                "position:absolute;right:0;top:0}\n      .w3-display-bottomleft{"
                "position:absolute;left:0;bottom:0}.w3-display-bottomright{"
                "position:absolute;right:0;bottom:0}\n      .w3-display-middle{"
                "position:absolute;top:50%;left:50%;transform:translate(-50%,"
                "-50%);-ms-transform:translate(-50%,-50%)}\n      "
                ".w3-display-left{"
                "position:absolute;top:50%;left:0%;transform:translate(0%,"
                "-50%);-ms-transform:translate(-0%,-50%)}\n      "
                ".w3-display-right{"
                "position:absolute;top:50%;right:0%;transform:translate(0%,"
                "-50%);-ms-transform:translate(0%,-50%)}\n      "
                ".w3-display-topmiddle{"
                "position:absolute;left:50%;top:0;transform:translate(-50%,"
                "0%);-ms-transform:translate(-50%,0%)}\n      "
                ".w3-display-bottommiddle{"
                "position:absolute;left:50%;bottom:0;transform:translate(-50%,"
                "0%);-ms-transform:translate(-50%,0%)}\n      "
                ".w3-display-container:hover .w3-display-hover{"
                "display:block}.w3-display-container:hover span.w3-display-hover{"
                "display:inline-block}.w3-display-hover{display:none}\n      "
                ".w3-display-position{position:absolute}\n      .w3-circle{"
                "border-radius:50%}\n      .w3-round-small{"
                "border-radius:2px}.w3-round,.w3-round-medium{"
                "border-radius:4px}.w3-round-large{"
                "border-radius:8px}.w3-round-xlarge{"
                "border-radius:16px}.w3-round-xxlarge{border-radius:32px}\n      "
                ".w3-row-padding,.w3-row-padding>.w3-half,"
                ".w3-row-padding>.w3-third,.w3-row-padding>.w3-twothird,"
                ".w3-row-padding>.w3-threequarter,.w3-row-padding>.w3-quarter,"
                ".w3-row-padding>.w3-col{padding:0 8px}\n      .w3-container,"
                ".w3-panel{padding:0.01em 16px}.w3-panel{"
                "margin-top:16px;margin-bottom:16px}\n      .w3-code,"
                '.w3-codespan{font-family:Consolas,"courier '
                'new";font-size:16px}\n      .w3-code{'
                "width:auto;background-color:#fff;padding:8px "
                "12px;border-left:4px solid #4CAF50;word-wrap:break-word}\n      "
                ".w3-codespan{color:crimson;background-color:#f1f1f1;padding-left"
                ":4px;padding-right:4px;font-size:110%}\n      .w3-card,"
                ".w3-card-2{box-shadow:0 2px 5px 0 rgba(0,0,0,0.16),0 2px 10px 0 "
                "rgba(0,0,0,0.12)}\n      .w3-card-4,.w3-hover-shadow:hover{"
                "box-shadow:0 4px 10px 0 rgba(0,0,0,0.2),0 4px 20px 0 rgba(0,0,0,"
                "0.19)}\n      .w3-spin{animation:w3-spin 2s infinite "
                "linear}@keyframes w3-spin{0%{transform:rotate(0deg)}100%{"
                "transform:rotate(359deg)}}\n      .w3-animate-fading{"
                "animation:fading 10s infinite}@keyframes fading{0%{"
                "opacity:0}50%{opacity:1}100%{opacity:0}}\n      "
                ".w3-animate-opacity{animation:opac 0.8s}@keyframes opac{from{"
                "opacity:0} to{opacity:1}}\n      .w3-animate-top{"
                "position:relative;animation:animatetop 0.4s}@keyframes "
                "animatetop{from{top:-300px;opacity:0} to{top:0;opacity:1}}\n     "
                " .w3-animate-left{position:relative;animation:animateleft "
                "0.4s}@keyframes animateleft{from{left:-300px;opacity:0} to{"
                "left:0;opacity:1}}\n      .w3-animate-right{"
                "position:relative;animation:animateright 0.4s}@keyframes "
                "animateright{from{right:-300px;opacity:0} to{"
                "right:0;opacity:1}}\n      .w3-animate-bottom{"
                "position:relative;animation:animatebottom 0.4s}@keyframes "
                "animatebottom{from{bottom:-300px;opacity:0} to{"
                "bottom:0;opacity:1}}\n      .w3-animate-zoom {"
                "animation:animatezoom 0.6s}@keyframes animatezoom{from{"
                "transform:scale(0)} to{transform:scale(1)}}\n      "
                ".w3-animate-input{transition:width 0.4s "
                "ease-in-out}.w3-animate-input:focus{width:100%!important}\n      "
                ".w3-opacity,.w3-hover-opacity:hover{"
                "opacity:0.60}.w3-opacity-off,.w3-hover-opacity-off:hover{"
                "opacity:1}\n      .w3-opacity-max{opacity:0.25}.w3-opacity-min{"
                "opacity:0.75}\n      .w3-greyscale-max,.w3-grayscale-max,"
                ".w3-hover-greyscale:hover,.w3-hover-grayscale:hover{"
                "filter:grayscale(100%)}\n      .w3-greyscale,.w3-grayscale{"
                "filter:grayscale(75%)}.w3-greyscale-min,.w3-grayscale-min{"
                "filter:grayscale(50%)}\n      .w3-sepia{filter:sepia("
                "75%)}.w3-sepia-max,.w3-hover-sepia:hover{filter:sepia("
                "100%)}.w3-sepia-min{filter:sepia(50%)}\n      .w3-tiny{"
                "font-size:10px!important}.w3-small{"
                "font-size:12px!important}.w3-medium{"
                "font-size:15px!important}.w3-large{font-size:18px!important}\n   "
                "   .w3-xlarge{font-size:24px!important}.w3-xxlarge{"
                "font-size:36px!important}.w3-xxxlarge{"
                "font-size:48px!important}.w3-jumbo{font-size:64px!important}\n   "
                "   .w3-left-align{text-align:left!important}.w3-right-align{"
                "text-align:right!important}.w3-justify{"
                "text-align:justify!important}.w3-center{"
                "text-align:center!important}\n      .w3-border-0{"
                "border:0!important}.w3-border{border:1px solid #ccc!important}\n "
                "     .w3-border-top{border-top:1px solid "
                "#ccc!important}.w3-border-bottom{border-bottom:1px solid "
                "#ccc!important}\n      .w3-border-left{border-left:1px solid "
                "#ccc!important}.w3-border-right{border-right:1px solid "
                "#ccc!important}\n      .w3-topbar{border-top:6px solid "
                "#ccc!important}.w3-bottombar{border-bottom:6px solid "
                "#ccc!important}\n      .w3-leftbar{border-left:6px solid "
                "#ccc!important}.w3-rightbar{border-right:6px solid "
                "#ccc!important}\n      .w3-section,.w3-code{"
                "margin-top:16px!important;margin-bottom:16px!important}\n      "
                ".w3-margin{margin:16px!important}.w3-margin-top{"
                "margin-top:16px!important}.w3-margin-bottom{"
                "margin-bottom:16px!important}\n      .w3-margin-left{"
                "margin-left:16px!important}.w3-margin-right{"
                "margin-right:16px!important}\n      .w3-padding-small{"
                "padding:4px 8px!important}.w3-padding{padding:8px "
                "16px!important}.w3-padding-large{padding:12px 24px!important}\n  "
                "    .w3-padding-16{"
                "padding-top:16px!important;padding-bottom:16px!important}.w3"
                "-padding-24{"
                "padding-top:24px!important;padding-bottom:24px!important}\n      "
                ".w3-padding-32{"
                "padding-top:32px!important;padding-bottom:32px!important}.w3"
                "-padding-48{"
                "padding-top:48px!important;padding-bottom:48px!important}\n      "
                ".w3-padding-64{"
                "padding-top:64px!important;padding-bottom:64px!important}\n      "
                ".w3-padding-top-64{"
                "padding-top:64px!important}.w3-padding-top-48{"
                "padding-top:48px!important}\n      .w3-padding-top-32{"
                "padding-top:32px!important}.w3-padding-top-24{"
                "padding-top:24px!important}\n      .w3-left{"
                "float:left!important}.w3-right{float:right!important}\n      "
                ".w3-button:hover{"
                "color:#000!important;background-color:#ccc!important}\n      "
                ".w3-transparent,.w3-hover-none:hover{"
                "background-color:transparent!important}\n      "
                ".w3-hover-none:hover{box-shadow:none!important}\n      /* Colors "
                "*/\n      .w3-amber,.w3-hover-amber:hover{"
                "color:#000!important;background-color:#ffc107!important}\n      "
                ".w3-aqua,.w3-hover-aqua:hover{"
                "color:#000!important;background-color:#00ffff!important}\n      "
                ".w3-blue,.w3-hover-blue:hover{"
                "color:#fff!important;background-color:#2196F3!important}\n      "
                ".w3-light-blue,.w3-hover-light-blue:hover{"
                "color:#000!important;background-color:#87CEEB!important}\n      "
                ".w3-brown,.w3-hover-brown:hover{"
                "color:#fff!important;background-color:#795548!important}\n      "
                ".w3-cyan,.w3-hover-cyan:hover{"
                "color:#000!important;background-color:#00bcd4!important}\n      "
                ".w3-blue-grey,.w3-hover-blue-grey:hover,.w3-blue-gray,"
                ".w3-hover-blue-gray:hover{"
                "color:#fff!important;background-color:#607d8b!important}\n      "
                ".w3-green,.w3-hover-green:hover{"
                "color:#fff!important;background-color:#4CAF50!important}\n      "
                ".w3-light-green,.w3-hover-light-green:hover{"
                "color:#000!important;background-color:#8bc34a!important}\n      "
                ".w3-indigo,.w3-hover-indigo:hover{"
                "color:#fff!important;background-color:#3f51b5!important}\n      "
                ".w3-khaki,.w3-hover-khaki:hover{"
                "color:#000!important;background-color:#f0e68c!important}\n      "
                ".w3-lime,.w3-hover-lime:hover{"
                "color:#000!important;background-color:#cddc39!important}\n      "
                ".w3-orange,.w3-hover-orange:hover{"
                "color:#000!important;background-color:#ff9800!important}\n      "
                ".w3-deep-orange,.w3-hover-deep-orange:hover{"
                "color:#fff!important;background-color:#ff5722!important}\n      "
                ".w3-pink,.w3-hover-pink:hover{"
                "color:#fff!important;background-color:#e91e63!important}\n      "
                ".w3-purple,.w3-hover-purple:hover{"
                "color:#fff!important;background-color:#9c27b0!important}\n      "
                ".w3-deep-purple,.w3-hover-deep-purple:hover{"
                "color:#fff!important;background-color:#673ab7!important}\n      "
                ".w3-red,.w3-hover-red:hover{"
                "color:#fff!important;background-color:#f44336!important}\n      "
                ".w3-sand,.w3-hover-sand:hover{"
                "color:#000!important;background-color:#fdf5e6!important}\n      "
                ".w3-teal,.w3-hover-teal:hover{"
                "color:#fff!important;background-color:#009688!important}\n      "
                ".w3-yellow,.w3-hover-yellow:hover{"
                "color:#000!important;background-color:#ffeb3b!important}\n      "
                ".w3-white,.w3-hover-white:hover{"
                "color:#000!important;background-color:#fff!important}\n      "
                ".w3-black,.w3-hover-black:hover{"
                "color:#fff!important;background-color:#000!important}\n      "
                ".w3-grey,.w3-hover-grey:hover,.w3-gray,.w3-hover-gray:hover{"
                "color:#000!important;background-color:#9e9e9e!important}\n      "
                ".w3-light-grey,.w3-hover-light-grey:hover,.w3-light-gray,"
                ".w3-hover-light-gray:hover{"
                "color:#000!important;background-color:#f1f1f1!important}\n      "
                ".w3-dark-grey,.w3-hover-dark-grey:hover,.w3-dark-gray,"
                ".w3-hover-dark-gray:hover{"
                "color:#fff!important;background-color:#616161!important}\n      "
                ".w3-pale-red,.w3-hover-pale-red:hover{"
                "color:#000!important;background-color:#ffdddd!important}\n      "
                ".w3-pale-green,.w3-hover-pale-green:hover{"
                "color:#000!important;background-color:#ddffdd!important}\n      "
                ".w3-pale-yellow,.w3-hover-pale-yellow:hover{"
                "color:#000!important;background-color:#ffffcc!important}\n      "
                ".w3-pale-blue,.w3-hover-pale-blue:hover{"
                "color:#000!important;background-color:#ddffff!important}\n      "
                ".w3-text-amber,.w3-hover-text-amber:hover{"
                "color:#ffc107!important}\n      .w3-text-aqua,"
                ".w3-hover-text-aqua:hover{color:#00ffff!important}\n      "
                ".w3-text-blue,.w3-hover-text-blue:hover{"
                "color:#2196F3!important}\n      .w3-text-light-blue,"
                ".w3-hover-text-light-blue:hover{color:#87CEEB!important}\n      "
                ".w3-text-brown,.w3-hover-text-brown:hover{"
                "color:#795548!important}\n      .w3-text-cyan,"
                ".w3-hover-text-cyan:hover{color:#00bcd4!important}\n      "
                ".w3-text-blue-grey,.w3-hover-text-blue-grey:hover,"
                ".w3-text-blue-gray,.w3-hover-text-blue-gray:hover{"
                "color:#607d8b!important}\n      .w3-text-green,"
                ".w3-hover-text-green:hover{color:#4CAF50!important}\n      "
                ".w3-text-light-green,.w3-hover-text-light-green:hover{"
                "color:#8bc34a!important}\n      .w3-text-indigo,"
                ".w3-hover-text-indigo:hover{color:#3f51b5!important}\n      "
                ".w3-text-khaki,.w3-hover-text-khaki:hover{"
                "color:#b4aa50!important}\n      .w3-text-lime,"
                ".w3-hover-text-lime:hover{color:#cddc39!important}\n      "
                ".w3-text-orange,.w3-hover-text-orange:hover{"
                "color:#ff9800!important}\n      .w3-text-deep-orange,"
                ".w3-hover-text-deep-orange:hover{color:#ff5722!important}\n      "
                ".w3-text-pink,.w3-hover-text-pink:hover{"
                "color:#e91e63!important}\n      .w3-text-purple,"
                ".w3-hover-text-purple:hover{color:#9c27b0!important}\n      "
                ".w3-text-deep-purple,.w3-hover-text-deep-purple:hover{"
                "color:#673ab7!important}\n      .w3-text-red,"
                ".w3-hover-text-red:hover{color:#f44336!important}\n      "
                ".w3-text-sand,.w3-hover-text-sand:hover{"
                "color:#fdf5e6!important}\n      .w3-text-teal,"
                ".w3-hover-text-teal:hover{color:#009688!important}\n      "
                ".w3-text-yellow,.w3-hover-text-yellow:hover{"
                "color:#d2be0e!important}\n      .w3-text-white,"
                ".w3-hover-text-white:hover{color:#fff!important}\n      "
                ".w3-text-black,.w3-hover-text-black:hover{"
                "color:#000!important}\n      .w3-text-grey,"
                ".w3-hover-text-grey:hover,.w3-text-gray,"
                ".w3-hover-text-gray:hover{color:#757575!important}\n      "
                ".w3-text-light-grey,.w3-hover-text-light-grey:hover,"
                ".w3-text-light-gray,.w3-hover-text-light-gray:hover{"
                "color:#f1f1f1!important}\n      .w3-text-dark-grey,"
                ".w3-hover-text-dark-grey:hover,.w3-text-dark-gray,"
                ".w3-hover-text-dark-gray:hover{color:#3a3a3a!important}\n      "
                ".w3-border-amber,.w3-hover-border-amber:hover{"
                "border-color:#ffc107!important}\n      .w3-border-aqua,"
                ".w3-hover-border-aqua:hover{border-color:#00ffff!important}\n    "
                "  .w3-border-blue,.w3-hover-border-blue:hover{"
                "border-color:#2196F3!important}\n      .w3-border-light-blue,"
                ".w3-hover-border-light-blue:hover{"
                "border-color:#87CEEB!important}\n      .w3-border-brown,"
                ".w3-hover-border-brown:hover{border-color:#795548!important}\n   "
                "   .w3-border-cyan,.w3-hover-border-cyan:hover{"
                "border-color:#00bcd4!important}\n      .w3-border-blue-grey,"
                ".w3-hover-border-blue-grey:hover,.w3-border-blue-gray,"
                ".w3-hover-border-blue-gray:hover{"
                "border-color:#607d8b!important}\n      .w3-border-green,"
                ".w3-hover-border-green:hover{border-color:#4CAF50!important}\n   "
                "   .w3-border-light-green,.w3-hover-border-light-green:hover{"
                "border-color:#8bc34a!important}\n      .w3-border-indigo,"
                ".w3-hover-border-indigo:hover{border-color:#3f51b5!important}\n  "
                "    .w3-border-khaki,.w3-hover-border-khaki:hover{"
                "border-color:#f0e68c!important}\n      .w3-border-lime,"
                ".w3-hover-border-lime:hover{border-color:#cddc39!important}\n    "
                "  .w3-border-orange,.w3-hover-border-orange:hover{"
                "border-color:#ff9800!important}\n      .w3-border-deep-orange,"
                ".w3-hover-border-deep-orange:hover{"
                "border-color:#ff5722!important}\n      .w3-border-pink,"
                ".w3-hover-border-pink:hover{border-color:#e91e63!important}\n    "
                "  .w3-border-purple,.w3-hover-border-purple:hover{"
                "border-color:#9c27b0!important}\n      .w3-border-deep-purple,"
                ".w3-hover-border-deep-purple:hover{"
                "border-color:#673ab7!important}\n      .w3-border-red,"
                ".w3-hover-border-red:hover{border-color:#f44336!important}\n     "
                " .w3-border-sand,.w3-hover-border-sand:hover{"
                "border-color:#fdf5e6!important}\n      .w3-border-teal,"
                ".w3-hover-border-teal:hover{border-color:#009688!important}\n    "
                "  .w3-border-yellow,.w3-hover-border-yellow:hover{"
                "border-color:#ffeb3b!important}\n      .w3-border-white,"
                ".w3-hover-border-white:hover{border-color:#fff!important}\n      "
                ".w3-border-black,.w3-hover-border-black:hover{"
                "border-color:#000!important}\n      .w3-border-grey,"
                ".w3-hover-border-grey:hover,.w3-border-gray,"
                ".w3-hover-border-gray:hover{border-color:#9e9e9e!important}\n    "
                "  .w3-border-light-grey,.w3-hover-border-light-grey:hover,"
                ".w3-border-light-gray,.w3-hover-border-light-gray:hover{"
                "border-color:#f1f1f1!important}\n      .w3-border-dark-grey,"
                ".w3-hover-border-dark-grey:hover,.w3-border-dark-gray,"
                ".w3-hover-border-dark-gray:hover{"
                "border-color:#616161!important}\n      .w3-border-pale-red,"
                ".w3-hover-border-pale-red:hover{"
                "border-color:#ffe7e7!important}.w3-border-pale-green,"
                ".w3-hover-border-pale-green:hover{"
                "border-color:#e7ffe7!important}\n      .w3-border-pale-yellow,"
                ".w3-hover-border-pale-yellow:hover{"
                "border-color:#ffffcc!important}.w3-border-pale-blue,"
                ".w3-hover-border-pale-blue:hover{border-color:#e7ffff!important} "
            )
        with a.style():
            a(
                "/* cyrillic-ext */\n      @font-face {\n\t  font-family: "
                "'Raleway';\n\t  font-style: normal;\n\t  font-weight: 400;\n\t  "
                "src: url("
                "https://fonts.gstatic.com/s/raleway/v28"
                "/1Ptxg8zYS_SKggPN4iEgvnHyvveLxVvaorCFPrEHJA.woff2) format("
                "'woff2');\n\t  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, "
                "U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;\n      }\n      /* "
                "cyrillic */\n      @font-face {\n\t  font-family: 'Raleway';\n\t "
                " font-style: normal;\n\t  font-weight: 400;\n\t  src: url("
                "https://fonts.gstatic.com/s/raleway/v28"
                "/1Ptxg8zYS_SKggPN4iEgvnHyvveLxVvaorCMPrEHJA.woff2) format("
                "'woff2');\n\t  unicode-range: U+0301, U+0400-045F, U+0490-0491, "
                "U+04B0-04B1, U+2116;\n      }\n      /* vietnamese */\n      "
                "@font-face {\n\t  font-family: 'Raleway';\n\t  font-style: "
                "normal;\n\t  font-weight: 400;\n\t  src: url("
                "https://fonts.gstatic.com/s/raleway/v28"
                "/1Ptxg8zYS_SKggPN4iEgvnHyvveLxVvaorCHPrEHJA.woff2) format("
                "'woff2');\n\t  unicode-range: U+0102-0103, U+0110-0111, "
                "U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, "
                "U+20AB;\n      }\n      /* latin-ext */\n      @font-face {\n\t  "
                "font-family: 'Raleway';\n\t  font-style: normal;\n\t  "
                "font-weight: 400;\n\t  src: url("
                "https://fonts.gstatic.com/s/raleway/v28"
                "/1Ptxg8zYS_SKggPN4iEgvnHyvveLxVvaorCGPrEHJA.woff2) format("
                "'woff2');\n\t  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, "
                "U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, "
                "U+A720-A7FF;\n      }\n      /* latin */\n      @font-face {\n\t "
                " font-family: 'Raleway';\n\t  font-style: normal;\n\t  "
                "font-weight: 400;\n\t  src: url("
                "https://fonts.gstatic.com/s/raleway/v28"
                "/1Ptxg8zYS_SKggPN4iEgvnHyvveLxVvaorCIPrE.woff2) format("
                "'woff2');\n\t  unicode-range: U+0000-00FF, U+0131, U+0152-0153, "
                "U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, "
                "U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, "
                "U+FFFD;\n      } "
            )
        with a.style():
            a(
                'body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}\n'
                ".semaphore-device { background: #000; width: 78px; height: 31px; "
                "padding: 5px; }\n"
                ".semaphore-light { height: 20px; width: 20px; "
                "background-color: #bbb; border-radius: 50%; display: "
                "inline-block; }"
            )
        a.title(_t=title)
