# Copyright 2018-2026 H2O.ai, Inc. All rights reserved.
import os
import traceback

import airium
import datatable
from matplotlib import pyplot

from h2o_sonar import errors
from h2o_sonar.lib.api import commons
from h2o_sonar.lib.api import explainers
from h2o_sonar.lib.api import explanations as e10s
from h2o_sonar.lib.api import formats as f5s
from h2o_sonar.lib.api import models
from h2o_sonar.lib.api import persistences
from h2o_sonar.lib.api import results
from h2o_sonar.lib.integrations import mv_adapter


try:
    from h2o_mv.core import mv_dataset
    from h2o_mv.core import mv_model
    from h2o_mv.recipes import calibscore
    from h2o_mv.recipes.calibscore import CalibrationScore

    HAS_H2O_MV = True
except ImportError:
    HAS_H2O_MV = False


class CalibrationScoreExplainer(
    explainers.Explainer, mv_adapter.ExplainerToMvTestAdapter
):
    """Calibration score explainer.

    @see https://docs.h2o.ai/wave-apps/h2o-model-validation/guide/tests
         /supported-validation-tests/calibration-score/calibration-score

    """

    _display_name = "Calibration Score"
    _description = (
        "A calibration score test enables you to assess how well the scores "
        "generated by a classification model align with the model's probabilities. "
        "In other words, the validation test can estimate how good the generated "
        "probabilities can be for a test dataset with real-world examples. "
        "In the case of a multi-class model, the validation test repeats the test "
        "for each target class. "
        ""
        "Explainer utilizes the Brier score to assess the model calibration of each "
        "target class. The Brier score ranges from 0 to 1, where 0 indicates "
        "a perfect calibration. After the test, explainer assigns a Brier score to "
        "the target class (or all target classes in the case of a multi-class model). "
        ""
        "In addition, the test generates a calibration score graph that visualizes "
        "the calibration curves to identify the ranges, directions, and magnitudes "
        "of probabilities that are off. H2O Model Validation adds a perfect "
        "calibration line (a diagonal line) for reference in this calibration "
        "score graph. "
        "Estimating how well the model is calibrated to real-world data is "
        "crucial when a classification model is used not only for "
        "complex decisions but supplies the probabilities for downstream tasks, "
        "such as pricing decisions or propensity to churn estimations."
    )
    _iid: bool = True
    _time_series: bool = True

    _supported_dataset_locators = [commons.ResourceLocatorType.handle]
    _supported_model_locators = [commons.ResourceLocatorType.handle]

    _regression: bool = False
    _binary: bool = True
    _multiclass: bool = True

    _global_explanation = True
    _explanation_types = [
        e10s.WorkDirArchiveExplanation,
    ]

    # param: training dataset ~ dataset
    # param: primary dataset ~ passed using test dataset argument
    # param: model ~ model
    PARAM_WORKER = "worker_connection_key"
    PARAM_NUMBER_OF_BINS = "number_of_bins"
    PARAM_BIN_STRATEGY = "bin_strategy"

    DEFAULT_NUMBER_OF_BINS = 10
    OPT_BIN_STRATEGY_QUANTILE = "uniform"
    OPT_BIN_STRATEGY_UNIFORM = "quantile"
    DEFAULT_BIN_STRATEGY = OPT_BIN_STRATEGY_QUANTILE

    _parameters = [
        explainers.ExplainerParam(
            param_name=PARAM_WORKER,
            description=(
                "The connection ID of the Driverless AI configured in the H2O "
                "Sonar configuration. Only Driverless AI servers with "
                "username and password authentication are supported."
            ),
            param_type=commons.ExplainerParamType.str,
            default_value=None,
            src=explainers.ExplainerParam.SRC_EXPLAINER_PARAMS,
        ),
        explainers.ExplainerParam(
            param_name=PARAM_NUMBER_OF_BINS,
            description=(
                "Defines the number of bins the explainer utilizes to divide "
                "the primary dataset."
            ),
            param_type=commons.ExplainerParamType.int,
            default_value=DEFAULT_NUMBER_OF_BINS,
            src=explainers.ExplainerParam.SRC_EXPLAINER_PARAMS,
        ),
        explainers.ExplainerParam(
            param_name=PARAM_BIN_STRATEGY,
            description=(
                "Defines the binning strategy - one of 'uniform' or 'quantile' - the "
                "explainer utilizes to bin the primary dataset."
            ),
            param_type=commons.ExplainerParamType.str,
            default_value=DEFAULT_BIN_STRATEGY,
            predefined=[
                OPT_BIN_STRATEGY_QUANTILE,
                OPT_BIN_STRATEGY_UNIFORM,
            ],
            src=explainers.ExplainerParam.SRC_EXPLAINER_PARAMS,
        ),
    ]
    _keywords = [
        explainers.Explainer.KEYWORD_COMPLIANCE_TEST,
        explainers.Explainer.KEYWORD_EXPLAINS_FEATURE_BEHAVIOR,
        explainers.Explainer.KEYWORD_H2O_MODEL_VALIDATION,
    ]
    _modules_needed_by_name = [
        mv_adapter.ExplainerToMvTestAdapter.MV_PYTHON_MODULE_NAME
    ]

    KEY_CLASSES_LABELS = "classes_labels"
    KEY_CLASSES_LEGENDS = "classes_legends"
    KEY_PLOTS_PATHS = "plots_paths"
    KEY_DATA = "data"
    KEY_BRIER_SCORE = "brier_score"
    KEY_CALIBRATION_CURVE = "calibration_curve"

    COL_TARGET = "Target"
    COL_SCORE = "Score"
    COL_PROB_TRUE = "prob_true"
    COL_PROB_PRED = "prob_pred"

    __RESULT_TITLE = "Calibration curve"
    RESULT_FILE_JSON = "mv_result.json"

    def __init__(self):
        explainers.Explainer.__init__(self)
        mv_adapter.ExplainerToMvTestAdapter.__init__(self)

        self.args = None
        self.log_name = "Calibration score"

    def check_compatibility(
        self,
        params: commons.CommonInterpretationParams | None = None,
        model: models.ExplainableModel | None = None,
        **explainer_params,
    ) -> bool:
        if not HAS_H2O_MV:
            self.logger.warning(
                self._check_compatibility_pckg_err_msg(mv_adapter.PACKAGE_NAME)
            )
            return False

        explainers.Explainer.check_compatibility(self, params, **explainer_params)
        mv_adapter.ExplainerToMvTestAdapter.check_mv_compatibility(self, explainer=self)

        self._resolve_explainer_params()

        # Driverless AI network connectivity
        try:
            self._probe_dai_connectivity(
                dai_connection_key=self.args.get(
                    CalibrationScoreExplainer.PARAM_WORKER, ""
                ),
                log_name=self.log_name,
                logger=self.logger,
            )
        except Exception as e:
            self.logger.warning(
                f"{self.log_name}: compatibility error {e}\n{traceback.format_exc()}"
            )
            return False

        mv_test = CalibrationScore(name=CalibrationScoreExplainer._display_name)
        mv_test.check_compatibility()

        return True

    def setup(
        self,
        model: models.ExplainableModel | None,
        persistence: persistences.ExplainerPersistence,
        key: str = "",
        params: commons.CommonInterpretationParams | None = None,
        **explainer_params,
    ):
        explainers.Explainer.setup(
            self,
            model=model,
            persistence=persistence,
            key=key,
            params=params,
            **explainer_params,
        )
        mv_adapter.ExplainerToMvTestAdapter.setup(
            self,
            h2o_sonar_config=self.config,
            persistence=persistence,
            logger=self.logger,
        )

        self._resolve_explainer_params()

        self.log_name = f"Calibration score {self.mli_key}/{self.key}"

    def explain(
        self,
        X: datatable.Frame,
        y: datatable.Frame | None = None,
        explanations_types: list = None,
        **e_params,
    ):
        #
        # calculation
        #
        mv_test = None
        try:
            # Driverless AI connection
            # get connection by name from the H2O Sonar configuration
            worker_connection_key = self.args.get(
                CalibrationScoreExplainer.PARAM_WORKER, ""
            )
            if not worker_connection_key:
                raise errors.MliError(
                    f"{self.log_name}: required worker connection name not specified "
                    f"in the explainer parameters"
                )
            # h2o_mv.platforms.driverless.platform.DriverlessPlatform:
            worker_connection = self._get_mv_dai_worker_by_key(
                connection_key=worker_connection_key,
                log_name=self.log_name,
            )
            if not worker_connection:
                raise errors.MliError(
                    f"{self.log_name}: worker connection '{worker_connection_key}' "
                    f"not found in the H2O Sonar configuration. "
                )
            self.mv_client.set_worker(worker_connection)
            self.mv_client.add_connection(worker_connection)  # returns platform w/ mvid

            primary_dataset: mv_dataset.MVDataset = mv_dataset.MVDataset(
                name="Training dataset",
                platform_mvid=worker_connection.mvid,
                platform_obj_key=X.resource_key,
            )
            primary_dataset = worker_connection.import_dataset(
                primary_dataset.platform_obj_key
            )
            primary_model: mv_model.MVModel = mv_model.MVModel(
                name="Model",
                platform_mvid=worker_connection.mvid,
                training_set_mvid=primary_dataset.mvid,
                platform_obj_key=self.model.resource_key,
            )

            primary_model = worker_connection.import_model(
                primary_model.platform_obj_key
            )

            number_of_bins: int = self.args.get(
                CalibrationScoreExplainer.PARAM_NUMBER_OF_BINS,
                CalibrationScoreExplainer.DEFAULT_NUMBER_OF_BINS,
            )
            curve_bin_strategy: str = self.args.get(
                CalibrationScoreExplainer.PARAM_BIN_STRATEGY,
                CalibrationScoreExplainer.DEFAULT_BIN_STRATEGY,
            )

            mv_test = calibscore.CalibrationScore(
                name=CalibrationScoreExplainer._display_name
            )
            mv_test.settings = calibscore.CalibrationScoreSettings(
                model=primary_model,
                primary_dataset=primary_dataset,
                curve_n_bins=number_of_bins,
                curve_bin_strategy=curve_bin_strategy,
            )
            mv_test.run()

            # assert MV test integrity
            mv_adapter.ExplainerToMvTestAdapter.assert_mv_test_status(self, mv_test)
        except Exception as e:
            self.logger.error(f"{self.log_name}: {e}\n{traceback.format_exc()}")
            raise e
        finally:
            if mv_test:
                self._dump_mv_test_log_to_explainer_log(mv_test.log)

        mv_result_dict = self.normalize_to_gom(mv_test.results)

        #
        # explanations
        #
        explanations = []

        # EXPLANATION: MV result ZIP archive
        mv_explanation = e10s.ModelValidationResultExplanation(
            explainer=self,
            display_name=self.display_name,
            display_category=e10s.Explanation.DISPLAY_CAT_COMPLIANCE,
        )
        mv_zip_format = f5s.ModelValidationResultArchiveFormat(
            explanation=mv_explanation,
            mv_test_type=mv_test,
            mv_test_name=mv_test.name,
            mv_test_id=mv_test.mvid,
            mv_test_results=mv_test.results,
            mv_test_settings=mv_test.settings,
            mv_test_log=mv_test.log,
            mv_test_artifacts={},
            persistence=self.persistence.store,
            logger=self.logger,
        )
        mv_explanation.add_format(mv_zip_format)
        explanations.append(mv_explanation)

        # EXPLANATION: work/ directory ZIP archive
        archive_explanation = self.create_explanation_workdir_archive(
            display_name=self.display_name,
            display_category=e10s.Explanation.DISPLAY_CAT_COMPLIANCE,
        )
        explanations.append(archive_explanation)

        # OPTIONAL EXPLANATION: HTML fragment
        if self.config and self.config.create_html_representations:
            try:
                explanations.append(self._normalize_html(mv_result_dict))
            except Exception as ex:
                self.logger.warning(
                    f"{self.log_name}: HTML representation creation failed: {ex}"
                )

        return explanations

    @staticmethod
    def _normalize_plot_calibration_curve(
        plot_data: datatable.Frame,
        plot_path: str,
        clazz_label: str = "",
        logger=None,
        log_name: str = None,
    ):
        try:
            this = CalibrationScoreExplainer

            # calibration curve
            xpoints = plot_data[:, this.COL_PROB_TRUE].to_list()[0]
            ypoints = plot_data[:, this.COL_PROB_PRED].to_list()[0]
            pyplot.plot(xpoints, ypoints, color="#000000", marker="o")

            # perfect calibration line
            xpoints = [0, 1]
            ypoints = [0, 1]
            pyplot.plot(xpoints, ypoints, color="#BBBB00", ls=":")

            # legends
            pyplot.title(
                f"{CalibrationScoreExplainer.__RESULT_TITLE} of class '{clazz_label}'"
            )
            pyplot.xlabel("Actual probability")
            pyplot.ylabel("Predicted probability")

            if plot_path:
                pyplot.savefig(plot_path, dpi=300)
            else:
                results.matplotlib_closing(True)

            # CLEAR figure to get ready for next plot
            pyplot.clf()
        except Exception as ex:
            if logger:
                logger.warning(
                    f"{log_name}: plot rendering failed: {ex}\n{traceback.format_exc()}"
                )

    def normalize_to_gom(self, mv_results) -> dict:
        # CalibrationScoreResults
        # - mv_test.results.class_labels # cls labels e.g. ['0', '1']
        # - mv_test.results.class_map # cls label -> str cls e.g. ['0': "EDU.0"]
        # - mv_test.results.brier_scores # pd.Frame: Target (cls label), Score
        # - mv_test.results.calibration_curves # pd.F: Target, prob_true, prob_pred

        this = CalibrationScoreExplainer

        # persist data which will normalized to work directory
        brier_scores = datatable.Frame(mv_results.brier_scores)
        brier_scores.to_csv(
            self.persistence.get_explainer_working_file("brier_scores.csv")
        )
        calibration_curves = datatable.Frame(mv_results.calibration_curves)
        calibration_curves.to_csv(
            self.persistence.get_explainer_working_file("calibration_curves.csv")
        )

        # NORMALIZE calibration curve data to GOM
        display_name = "Calibration curve"
        (
            global_idx_dict,
            _,
        ) = f5s.GlobalFeatImpJSonDatatableFormat.serialize_index_file(
            classes=mv_results.class_labels,
            doc=CalibrationScoreExplainer._description,
        )
        cc_explanation = e10s.GlobalDataFrameExplanation(
            explainer=self,
            display_name=display_name,
            display_category=e10s.Explanation.DISPLAY_CAT_DAI_MODEL,
        )
        cc_dt_format = f5s.DatatableCustomExplanationFormat(
            explanation=cc_explanation,
            frame=calibration_curves,
            frame_file="",
            persistence=self.persistence.store,
        )
        cc_explanation.add_format(cc_dt_format)

        # prepare data for the plot rendering (HTML format) to work directory
        mv_result_per_class = {
            this.KEY_CLASSES_LABELS: mv_results.class_labels,
            this.KEY_CLASSES_LEGENDS: mv_results.class_map,
            this.KEY_PLOTS_PATHS: [],
            this.KEY_DATA: {
                clazz: {this.KEY_BRIER_SCORE: None, this.KEY_CALIBRATION_CURVE: None}
                for clazz in mv_results.class_labels
            },
        }
        for i, clazz in enumerate(mv_results.class_labels):
            cls_label = mv_results.class_map[clazz]
            cls_brier_score = brier_scores[i, this.COL_SCORE]
            cls_calib_curve_data = calibration_curves[
                datatable.f[this.COL_TARGET] == clazz, :
            ]
            plot_path = self.persistence.get_explainer_working_file(
                f"calibration_curve_{i}.png"
            )

            mv_result_per_class[this.KEY_PLOTS_PATHS].append(plot_path)
            mv_result_per_class[this.KEY_DATA][clazz][this.KEY_BRIER_SCORE] = (
                cls_brier_score
            )
            mv_result_per_class[this.KEY_DATA][clazz][this.KEY_CALIBRATION_CURVE] = (
                cls_calib_curve_data.to_dict()
            )

            self._normalize_plot_calibration_curve(
                plot_data=cls_calib_curve_data,
                plot_path=plot_path,
                clazz_label=cls_label,
            )
        self.persistence.save_json(
            data=mv_result_per_class,
            path=self.persistence.get_explainer_working_file(
                CalibrationScoreExplainer.RESULT_FILE_JSON
            ),
        )

        return mv_result_per_class

    def _normalize_html(self, mv_result_dict: dict):
        plots_paths = mv_result_dict[CalibrationScoreExplainer.KEY_PLOTS_PATHS]

        e_type = e10s.GlobalHtmlFragmentExplanation

        global_explanation = e10s.GlobalHtmlFragmentExplanation(
            explainer=self,
            display_name=CalibrationScoreExplainer._display_name,
            display_category=e10s.Explanation.DISPLAY_CAT_DAI_MODEL,
        )

        # HTML format
        html_src = airium.Airium()

        with html_src.b():
            for i, plot_path in enumerate(plots_paths):
                with html_src.b():
                    clazz = mv_result_dict[
                        CalibrationScoreExplainer.KEY_CLASSES_LABELS
                    ][i]
                    brier_score = mv_result_dict[CalibrationScoreExplainer.KEY_DATA][
                        clazz
                    ][CalibrationScoreExplainer.KEY_BRIER_SCORE]
                    html_src(f"Brier score: {brier_score}")

                img_format_file = self.persistence.get_relative_path(
                    self.persistence.get_explanation_file_path(
                        explanation_type=e_type.explanation_type(),
                        explanation_format=f5s.HtmlFormat.mime,
                        explanation_file=os.path.basename(plot_path),
                    )
                )
                with html_src.div():
                    html_src.img(
                        src=img_format_file,
                        alt=CalibrationScoreExplainer.__RESULT_TITLE,
                        # ensure that image will not overflow enclosing <div/>
                        style=(
                            "height: 100%; max-width: 100%; display: block; "
                            "margin: auto;"
                        ),
                    )
                    html_src.br()

        report_text = str(html_src)
        report_file_name = f"{self.persistence.FILE_EXPLANATION}.html"
        report_path = self.persistence.get_explainer_working_file(report_file_name)
        with open(report_path, mode="w") as file:
            file.write(report_text)

        # add HTML format (will copy report and image files from work)
        html_format = f5s.HtmlFormat(
            explanation=global_explanation,
            format_data="",  # data will be updated later
            format_file=os.path.join(
                self.persistence.get_explainer_working_dir(),
                report_file_name,
            ),
            extra_format_files=plots_paths,
            persistence=self.persistence.store,
        )
        global_explanation.add_format(html_format)

        return global_explanation

    class Result(explainers.ExplainerResult):
        def __init__(
            self,
            persistence: persistences.ExplainerPersistence,
            explainer_id: str = "",
            h2o_sonar_config=None,
        ):
            self.explainer_id = explainer_id
            self.explanation = e10s.GlobalGroupedBarChartExplanation
            self.format = f5s.CustomArchiveZipFormat
            self.config = h2o_sonar_config

            explainers.ExplainerResult.__init__(
                self,
                persistence=persistence,
                explainer_id=self.explainer_id,
                explanation=self.explanation,
                explanation_format=self.format,
                h2o_sonar_config=self.config,
            )

            self.log_name = "Segment performance"

        def data(self) -> dict:
            return self.persistence.store.load_json(
                self.persistence.get_explainer_working_file(
                    CalibrationScoreExplainer.RESULT_FILE_JSON
                )
            )

        def _raw_data(self) -> dict:
            return self.data()

        def plot(
            self,
            *,
            clazz: str = "",
            file_path: str = "",
        ):
            data = self.data()
            clazz = clazz or data[CalibrationScoreExplainer.KEY_CLASSES_LABELS][0]

            CalibrationScoreExplainer._normalize_plot_calibration_curve(
                plot_data=datatable.Frame(
                    data[CalibrationScoreExplainer.KEY_DATA][clazz][
                        CalibrationScoreExplainer.KEY_CALIBRATION_CURVE
                    ]
                ),
                plot_path=file_path,
                clazz_label=clazz,
            )

        def summary(self, **kwargs) -> dict:
            return self.params()

    def get_result(self) -> Result:
        return CalibrationScoreExplainer.Result(
            persistence=self.persistence,
            explainer_id=CalibrationScoreExplainer.explainer_id(),
            h2o_sonar_config=self.config,
        )
