# -*- coding: utf-8 -*-
# Copyright 2018-2026 H2O.ai, Inc. All rights reserved.
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath("../.."))


# -- Project information -----------------------------------------------------

project = "H2O Sonar"
copyright = "2018-2026 H2O.ai, Inc. All rights reserved."
author = "H2O.ai"

try:
    about_info = {}
    with open("../../h2o_sonar/BUILD_INFO.txt") as f:
        exec(f.read(), about_info)
    # the short X.Y version
    version = about_info["version"]
    # the full version, including alpha/beta/rc tags
    release = about_info["version"]
except Exception:
    import os
    import re

    version_file = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "../../make/version.mk")
    )
    if os.path.isfile(version_file):
        txt = open(version_file, "rt").read()
    else:
        txt = ""
    mm = re.search(r'BASE_VERSION = (.*)', txt)
    version = release = mm.group(1) if mm else "0.0.0"

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    # core Sphinx library for auto html doc generation from docstrings
    "sphinx.ext.autodoc",
    # link to other project's documentation (see mapping below)
    "sphinx.ext.intersphinx",
    # Markdown includes
    # "sphinx_mdinclude",
    # include Jupyter Notebooks
    "nbsphinx",
    # MathJax support
    "sphinx.ext.mathjax",
    "sphinx.ext.ifconfig",
    # include source code (not use for customer documentation)
    # "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    # numpy style docstrings support
    "numpydoc",
    # create neat summary tables for modules/classes/methods etc
    "sphinx.ext.autosummary",
    # automatically document param types (less noise in class signature)
    # "sphinx_autodoc_typehints",  # disabled @ failure @ 0.9.0 release merge to main
    # turn sections to anchors so that it's possible to ref them
    "sphinx.ext.autosectionlabel",
]

# numpydoc to skip class members ("Members" sections not written in docstrings)
numpydoc_show_class_members = False
# generate autosummary even if no references
autosummary_generate = True
autosummary_imported_members = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = [".rst", ".md"]

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "**.ipynb_checkpoints"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# Configure nbsphinx to use 'python' lexer instead of 'ipython3'
# This prevents "Pygments lexer name 'ipython3' is not known" warnings
nbsphinx_codecell_lexer = "python"

# Allow duplicate labels in notebooks
# Notebooks follow standard structure with common section headers (Interpretation, etc.)
# This suppresses warnings about duplicate labels across notebooks
nbsphinx_allow_duplicate_labels = True

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages. See the documentation for
# a list of builtin themes.
html_theme = "sphinx_rtd_theme"
html_title = f"{project} {version}"
# html_short_title = None
# html_logo = None
# html_favicon = None
# html_static_path = ['_static']
# html_domain_indices = False
# html_use_index = False
# html_show_sphinx = False
# htmlhelp_basename = 'H2oSonarDoc'
# html_show_sourcelink = False

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "canonical_url": "https://h2o-sonar.readthedocs.io/en/latest/",
    "style_external_links": True,
    "collapse_navigation": True,
    "sticky_navigation": True,
    "titles_only": True,
    "logo_only": False,
    # Note: display_version was removed in sphinx-rtd-theme 3.0
    # Version is now displayed via custom context variable below
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# TODO H2O.ai theme disabled as + and - tree icons are broken
# html_static_path = ["sphinx_rtd_theme/static", "_static"]
html_static_path = ["_static"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = ["sphinx_rtd_theme/source/css"]

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "h2o_sonar-2doc"

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "h2o_sonar-2.tex", "h2o_sonar-2 Documentation", "H2O.ai", "manual"),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "h2o_sonar-2", "h2o_sonar-2 Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "h2o_sonar-2",
        "h2o_sonar-2 Documentation",
        author,
        "h2o_sonar-2",
        "One line description of project.",
        "Miscellaneous",
    ),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]


# -- Extension configuration -------------------------------------------------

# -- Custom setup ------------------------------------------------------------

html_favicon = 'images/favicon.ico'

# Add version to HTML context for display in theme
# sphinx-rtd-theme 3.0 removed display_version option, so we add it via context
html_context = {
    'display_version': True,
    'current_version': version,
    'version': version,
    'versions': [('latest', version)],
}


def setup(app):
    # generate custom.css with current version dynamically in build output
    import os

    def write_custom_css(app):
        """Write custom.css to build output directory before build starts."""
        custom_css_content = f"""/* Add version display under project title in sidebar */
.wy-side-nav-search .icon.icon-home::after {{
    content: " {version}";
    font-size: 0.85em;
    color: #54585a;
    font-weight: normal;
    display: block;
    margin-top: 5px;
}}
"""
        # write to build output _static directory, not source _static
        static_dir = os.path.join(app.outdir, "_static")
        os.makedirs(static_dir, exist_ok=True)
        custom_css_path = os.path.join(static_dir, "custom.css")
        with open(custom_css_path, "w") as f:
            f.write(custom_css_content)

    # connect to builder-inited event to write CSS before build processes static files
    app.connect("builder-inited", write_custom_css)

    app.add_css_file("code.css")
    app.add_css_file("custom.css")
